### ISSUE TITLE
"Error getting webui settings" with reverse proxy

### ISSUE THREAD

**Issue by f1sherman** [OliveTin/OliveTin#100]
**Describe the bug**
I have a virtual host reverse proxy that proxies port 443 (HTTPS) to port 1337 for Olivetin. However, it seems that there is no way to make Olivetin aware of this (at least as far as I can tell from the docs), so it tries to fetch settings using port 1337, which fails.

**To Reproduce**
1. Set up a virtual host reverse proxy that proxies port 443 (HTTPS) to port 1337
2. Install/Start Olivetin
3. Access Olivetin at the proxied virtual host using port 443

**Expected behavior**
Olivetin will use the same port as the parent page to fetch settings

**Comment by jamesread** [comment]
Hey @f1sherman , first of all, congrats on Issue #100  :partying_face: :fireworks: :tada: !

You didn't mention which reverse proxy you are using, but there is a good deal of documentation here - just mentioning it for other people that might find this issue; https://docs.olivetin.app/reverse-proxies.html 

OliveTin should "auto detect" external addresses, but it cannot do this every time. If you wanted to manually set it in the config file, the correct option is `externalRestAddress`, eg: 

````
...
logLevel: Info
externalRestAddress: http://myserver/OliveTin`
actions: 
...
````

**Comment by f1sherman** [comment]
@jamesread thank you! I was using nginx as my reverse proxy (vhost based). Thanks for passing on that config property, I'll make sure that is set going forward.
