### ISSUE TITLE
Apache config for USER

### ISSUE THREAD

**Issue by mangaxx** [OliveTin/OliveTin#105]
Hi,
in /var/log/messages i find the record
Feb 15 15:31:07 bfiskolive01p OliveTin[1101]: level="info" msg="UserFromContext" usergroup="" username=""

with no value inside
The access to OliveTin is made by Apache on redhat joined to our ldap directory
<Location />
  AuthType Basic
  AuthBasicProvider ldap
  AuthName "Olive"
  AuthLDAPInitialBindAsUser on
  AuthLDAPSearchAsUser      on
  AuthLDAPCompareAsUser     on
  AuthLDAPInitialBindPattern (.+) $1@XXX.XXX.XXX.com
  AuthLDAPURL ldaps://XXX.XXX.XXX.com/OU=XXX,DC=XXX,DC=XXX,DC=xxxxxxxx,DC=com?samaccountname?sub

can you suggest me where i'm wrong?
What do I have to do to log the user tha make that operation?
Thanks

**Comment by jamesread** [comment]
Hey @mangaxx , thanks for reporting this issue. 

This is actually a log message that is providing info that OliveTin did not find a valid "user" from JWT authentication. At the moment OliveTin does not pick up Basic auth type, but this is absolutely something I'm interested in adding in the future. You're actually the first person to mention this actually. 

JWT is a lot more complex than basic auth - so, it should be easy :-) Do  you know what format Apache is passing the user header to OliveTin? That would save me setting up my own Apache instance! I think it's in something like an `Authorization:` header, or similar.

**Comment by mangaxx** [comment]
I'm working on it
I'll be back as soon as possible
Thanks

**Comment by mangaxx** [comment]
I found this information:

For example, if the browser uses Aladdin as the username and open sesame as the password, then the field's value is the Base64 encoding of Aladdin:open sesame, or QWxhZGRpbjpvcGVuIHNlc2FtZQ==. Then the Authorization header field will appear as:

Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==

let me know if it is useful!

Thanks

**Comment by jamesread** [comment]
Closing this as it's basically similar to #141
