### ISSUE TITLE
WebUI not loading due to 404 on marshaller.js

### ISSUE THREAD

**Issue by ramesh-lingappan** [OliveTin/OliveTin#124]
**Describe the bug**
Hi, I just installed OliveTin via [deb package](https://github.com/OliveTin/OliveTin/releases/latest/download/OliveTin_linux_arm64.deb) on a Debian OS. The application is running, but when i visit the webUI on port 1337, i can only see broken dashboard where i cannot click anything. 

When i inspected the network tab, i see one resource is failed to load due to 404 error

```
http://localhost:1337/js/marshaller.js -> 404
```
But the following path works, without the /js prefix, so does the /main.js file 

```
http://localhost:1337/marshaller.js -> 200
```
Source code: https://github.com/OliveTin/OliveTin/blob/main/webui/main.js#L3

Any clue how i can resolve this? its the first time am trying this application

**To Reproduce**
1. Install deb package 
2. Go to the WebUI at http://{youserver}:1337
3. you can see broken dashboard 
4. In network /js/marshaller.js loading is failed with 404

![Screenshot 2023-03-03 at 3 57 16 PM](https://user-images.githubusercontent.com/4492145/222754012-64ebc249-3aaf-406a-a472-2ab754f69f00.png)
![Screenshot 2023-03-03 at 4 03 16 PM](https://user-images.githubusercontent.com/4492145/222754469-d90491e7-01b5-4d9d-b276-8f3406df4e79.png)

**Comment by maskcc** [comment]
> 
You can copy  the .js files from /var/www/olivetin to /var/www/olivetin/js folder, this is a easy way to solve this problem.

**Comment by jamesread** [comment]
Hey folks, thanks for reporting this, it looks like an issue has creeped up in recent builds. I have 4 out of 5 days off work next week, and I plan on doing some OliveTin'ing - so will take a look at this for you next week. Thanks for your patience in the meantime!

**Comment by mcdowellster** [comment]
I ended up building my own with symbolic links from your tarball for now :)

**Comment by mcdowellster** [comment]
Yes, I used the deb package originally. It looked like config.yml was doing nothing until I changed the port and it did indeed change it. Inspected the page with my browser and saw the missing .js files -> it was referencing /js/*.js exactly as @maskcc noted above

**Comment by jamesread** [comment]
@maskcc , @mcdowellster , @ramesh-lingappan , could any of you check a recent release - like 2023.10.25 from yesterday - this issue should have been fixed a long time ago.

**Comment by mcdowellster** [comment]
Can confirm that recent package works as expected 👍
