### ISSUE TITLE
Publish Docker images to GitHub Container Registry

### ISSUE THREAD

**Issue by flammable** [OliveTin/OliveTin#133]
**Is your feature request related to a problem? Please describe.**
Last week, Docker (the company) [sent out an email](https://blog.alexellis.io/docker-is-deleting-open-source-images/) to a bunch of users who host images on Docker Hub, informing them that their free plan was about to end. Although they've since [walked back the decision](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/), Docker Hub doesn't seem like the safest place to host Docker images at the moment.

**Describe the solution you'd like**
Would it be possible to also publish to the GitHub Container Registry? GHCR is free for projects hosted at GitHub, so OliveTin would qualify.

**Describe alternatives you've considered**
If it's not desirable to switch from Docker Hub to GHCR entirely, would it be possible to publish to both locations to give people time to migrate, or see what happens long-term? Personally, I would switch, but some people might not notice that GHCR is an option right away.

**Additional context**
Docker Hub also limits the number of pulls that free accounts can do, so GHCR would be an improvement in this regard, too. Thanks for considering this!

**Comment by flammable** [comment]
Excellent article! I agree 100%. Thanks!

**Comment by jamesread** [comment]
It is done; https://github.com/OliveTin/OliveTin/pkgs/container/olivetin :-)

**Comment by flammable** [comment]
Woo thank you!
