### ISSUE TITLE
Auth with password

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#140]
This might be useful for very simple, quick and easy setups. 

HTTP Basic auth could be considered if it doesn't add too much code bloat to the HTTP Servers. 

I'm not interested in implementing per-user passwords, as we'll quickly get into a situation of having to implement a full user management stuff. I'm thinking a simple config option like AuthSimpleAdminPassword. 

As suggested by @bmitchinson in #30 (and some others) in other places.

**Comment by jamesread** [comment]
![image](https://github.com/user-attachments/assets/ccc7d17c-1cc7-435c-99d9-55dbb9a91326)

Hey all, OliveTin now supports login via username/password, and OAuth2 was added recently. On top of this, it also supports trusted headers and JWT tokens. https://docs.olivetin.app/local-users.html

**Comment by hialvaro** [comment]
Hi @jamesread can users defined via local auth have a group? I took a look at the code and it seems like it's not supported

**Comment by jamesread** [comment]
> Hi @jamesread can users defined via local auth have a group? I took a look at the code and it seems like it's not supported

Yep: https://github.com/OliveTin/OliveTin/blob/be5ddda0207212be336a618535488cede9333085/internal/config/config.go#L151

I need to document it / test it.
