### ISSUE TITLE
Auth with trusted HTTP Header

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#141]
This was originally the design for auth support in OliveTin/OliveTin#30 - which grew too big. Moving the discussion here. See https://github.com/OliveTin/OliveTin/issues/30#issue-1062913412 for context. 

As @jacksgt points out - I did get half way through implementing this (in https://github.com/OliveTin/OliveTin/commit/0335e58b128c3ffd72c8eb70da781e5855685239 and probably some other commits), but it needs docs support, and some testing.

@jacksgt - it would be good if you're able to test this with you setup - I don't have a reverse proxy currently configured that supports auth via headers (I will set one up - but I'm limited on time!). 

- [x] OliveTin/docs.olivetin.app#10
- [x] Add some tests for trusted HTTP Header auth

**Comment by jacksgt** [comment]
Hey, thanks for your time and effort!

I will take a look at the items listed above in the coming days / weeks.

**Comment by jamesread** [comment]
@Typhonragewind hey, what setup (proxy, proxy config, and OliveTin config) are you using please? Let's debug it together.

**Comment by Typhonragewind** [comment]
> @Typhonragewind hey, what setup (proxy, proxy config, and OliveTin config) are you using please? Let's debug it together.

As my reverse proxy i use SWAG coupled with Authentik with the following config for OliveTin:
`server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name tin.*;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    # enable for Authentik (requires authentik-location.conf in the location block)
    include /config/nginx/authentik-server.conf;

    location / {
        # enable for Authentik (requires authentik-server.conf in the server block)
        include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app lan_ip;
        set $upstream_port 1337;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

}`

The content of authentik_location is:
`## Send a subrequest to Authentik to verify if the user is authenticated and has permission to access the resource.
auth_request /outpost.goauthentik.io/auth/nginx;
## If the subreqest returns 200 pass to the backend, if the subrequest returns 401 redirect to the portal.
error_page 401 = @goauthentik_proxy_signin;

## Translate response headers from Authentik into variables
auth_request_set $authentik_email $upstream_http_x_authentik_email;
auth_request_set $authentik_groups $upstream_http_x_authentik_groups;
auth_request_set $authentik_name $upstream_http_x_authentik_name;
auth_request_set $authentik_uid $upstream_http_x_authentik_uid;
auth_request_set $authentik_username $upstream_http_x_authentik_username;

## Inject the response header variables into the request made to the actual upstream
proxy_set_header X-authentik-email $authentik_email;
proxy_set_header X-authentik-groups $authentik_groups;
proxy_set_header X-authentik-name $authentik_name;
proxy_set_header X-authentik-uid $authentik_uid;
proxy_set_header X-authentik-username $authentik_username;

## Include the Set-Cookie header if present.
auth_request_set $set_cookie $upstream_http_set_cookie;
add_header Set-Cookie $set_cookie;`

My Olivetin config is:
`# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

AuthHttpHeaderUsername: "X-authentik-username"

defaultPermissions:
    view: false
    exec: false

accessControlLists:
    - name: Admin
      addToEveryAction: true
      matchUsernames:
      - typhon
      permissions:
        view: true
        exec: true

    - name: "user2"
      matchUsernames:
      - "user2"
      permissions:
        view: true
        exec: true

    - name: "user3"
      matchUsernames:
      - "user3"
      permissions:
        view: true
        exec: true

# Actions (buttons) to show up on the WebUI:
actions:   
  # This will send 1 ping (-c 1)
- title: Ping Google.com
  shell: ping google.com -c 1
  icon: ping

- title: Restart Foundry (user3)
  shell: docker restart foundry_user3
  icon: "&#128260;"
  timeout: 30
  acls:
     - "aez"

#- title: Restore Last Backup Foundry (user3)
 # shell: /docker_volumes/management/foundry_user3_restorebackup.sh
  #icon: "&#9851;"
  #timeout: 30

- title: Restart Foundry (Typhon)
  shell: docker restart foundry
  icon: "&#128260;"
  timeout: 30

- title: Restart Foundry (user2)
  shell: docker restart foundry_user2
  icon: "&#128260;"
  timeout: 30
  acls:
     - "user2"`

**Comment by jamesread** [comment]
Just a note that the logs have been considerably improved in the 2023.11.20 release to help debug trusted header Auth.

**Comment by Typhonragewind** [comment]
> Just a note that the logs have been considerably improved in the 2023.11.21 release to help debug trusted header Auth.

Sure, i'll update and report soon!

**Comment by jamesread** [comment]
https://docs.olivetin.app/trusted-header.html

@jacksgt @Typhonragewind Would you be willing to help test with a recent OliveTin release?

**Comment by Typhonragewind** [comment]
> https://docs.olivetin.app/trusted-header.html
> 
> @jacksgt @Typhonragewind Would you be willing to help test with a recent OliveTin release?

I've been pretty swamped with life in general, but I'll try to do it this weekend!

**Comment by jamesread** [comment]
No hurry @Typhonragewind - we all have that problem! :-) I'll leave the issue open until we all resolve it!

**Comment by Typhonragewind** [comment]
@jamesread So, i updated and tested it out, still no luck.

I checked the logs and it seems the problem is on my side xD

`level="warning" msg="Config has AuthHttpHeaderUsername set to X-authentik-username, but it was not found"`

**Comment by jamesread** [comment]
So that sounds like your authentik proxy isn't sending that header to OliveTin - as it's complaining it can't find that header in the request.

**Comment by jamesread** [comment]
Okay, you can enable more logging in OliveTin to help you out; 

````
logDebugOptions: 
    singleFrontendRequests: true
    singleFrontendRequestHeaders: true
````

Then you can see exactly what OliveTin is being sent by your proxy.

**Comment by jamesread** [comment]
@Typhonragewind Are you still looking at this, or still haveing issues? I'd be keen to close this issue, but want to make sure you've got what you need.

**Comment by Typhonragewind** [comment]
@jamesread Hey! Sorry for the delay in communications...been quite the week here.

This issue is fixed, it was all on my side (i thought i had posted the result here, but it seems i might be going insane). There was a misconfiguration in my NGINX reverse proxy that was causing these headers to not be sent from Authentik.

The header auth works flawlessly now!

The extended logs form OliveTin were a great help to diagnose this, thank you!
