### ISSUE TITLE
Textfield and Dropdown

### ISSUE THREAD

**Issue by HeyIJoNNy** [OliveTin/OliveTin#143]
I am working with windows and trying to start a batch with 2 parameters.

This is what I build:

actions:
  - title: Stop Server
    shell: start D:\Control\OliveTin-windows-amd64\InjectCommand.bat "{{ batchname }}" "{{ command }}"
    arguments:
      - name: batchname
        choices:
          - title: Server1
            value: Start_Server1
          - title: Server2
            value: Start_Server2
      - name: command
        type: ascii_sentence

The console:

level="info" msg="Before Parse Args" cmd="start D:\\Control\\OliveTin-windows-amd64\\InjectCommand.bat \"{{ batchname }}\" \"{{ command }}\""
level="info" msg="After Parse Args" cmd="start D:\\Control\\OliveTin-windows-amd64\\InjectCommand.bat \"Start_Server1\" \"stop\""
level="info" msg="Action starting" timeout="3" title="Stop Server"

Looks like the \" added there are the problem. Can I prevent that?

**Comment by jamesread** [comment]
Hey @HeyIJoNNy , yep, in your `shell: ` like, you've added quotes around the arguments - OliveTin doesn't need or expect these to be quoted - so it's passing them through to your shell literally. Just remove them and you should have a working command :-)

**Comment by jamesread** [comment]
Ah, the " quotes in the example for `echo` are needed, but yeah, not in most cases. Glad you got it solved!
