### ISSUE TITLE
Lock jobs to prevent many executions at once

### ISSUE THREAD

**Issue by singiamtel** [OliveTin/OliveTin#146]
**Is your feature request related to a problem? Please describe.**
I have some long-running jobs, and sometimes 2 people try to run them at once, making them crash in very unpredictable ways

**Describe the solution you'd like**
It would be great to have "locking" buttons, which means nobody can start the request again until it finished the last one

**Describe alternatives you've considered**
Doing the locking myself in the scripts, it works fine, but of course it would be more convenient to just have a setting here

**Additional context**
I'd be happy to try to make the PR myself if you'd like. Great project btw!

**Comment by jamesread** [comment]
Thanks @singiamtel , this has been on the todo list for a while, just implemented it. It will be available in the next release.

**Comment by jamesread** [comment]
Version 2023.10.25 contains support for macConcurrent. And it is documented here: https://docs.olivetin.app/concurrency.html

@singiamtel , would you mind testing this and providing feedback?

**Comment by singiamtel** [comment]
Working with no config change, amazing! Very appreciated :)

<img width="1367" alt="image" src="https://github.com/OliveTin/OliveTin/assets/47090312/94dee13a-ec89-453a-80e1-fd9401e116ec">
