### ISSUE TITLE
Visual separator in html

### ISSUE THREAD

**Issue by mikch06** [OliveTin/OliveTin#148]
If we can separate different icons with a line or some other visual <hr> would be very nice. 
I try to arrange different steps of a project on one view. So it would be possible to arrange it stepwise. 

Thx in advance!

**Comment by jamesread** [comment]
Hey @mikch06 , sorry it's been a while since I've been looking at OliveTin issues.

What sort of groupings would you have? One possibility I thought of was to have separate "dashboards" of icons, that you could switch between with a sidebar. Would that work for you?

**Comment by mikch06** [comment]
Hi James,
thx a lot - already forgotten to opened this issue :D 

I think - also just a \<hr> horizontal line or similar would be enough. 

I just like to seperate different kind of tasks: e.g.

> checking for updates

> do the updates

> boot the machines. 


But every kind of separation is appreciated.

Thank you!

**Comment by jamesread** [comment]
Duplicate of #64

**Comment by mikch06** [comment]
thx!
