### ISSUE TITLE
Customizable title

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#15]
Originally described by PDXUser. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
How about a customize-able page header?  Something where we could input in the config file or in the web interface.  I can envision something like "Server Command Center" or "Server Control"

![header_idea.png](https://user-images.githubusercontent.com/2025715/126860794-1b864f5c-4600-438d-9900-3dcbe07097c8.png)

Notes; 

- Probably something for GetButtons, after entity support is implemented.
- This would go in the config file

**Comment by ManOki** [comment]
Also update the html header title tag accordingly.

**Comment by ManOki** [comment]
Configurable via config.yaml `pageTitle: NAS` in [current release](https://github.com/OliveTin/OliveTin/blob/244404afbc2fcd854476997370cde923ee54e207/internal/config/config.go#L83)

**Comment by jamesread** [comment]
Hey, I've just had some time to work on this, and wanted to share a development video that calls out some relevant changes. Does this fix the issue for you?

https://youtu.be/vWAD04Wpa8U

**Comment by jamesread** [comment]
#236 Fixes the Application Title
