### ISSUE TITLE
Add folders to group actions

### ISSUE THREAD

**Issue by TheRaven500** [OliveTin/OliveTin#151]
It would be very nice to create something like folders. With such a function it is possible to group functions.

Example:
Kitchen (folder) -> light on (button), light off (button)
Livingroom (folder) -> light on (button), light off (button)
Server-Control (folder) -> restart (button), power off (button).

This way you see only three buttons on start page and not six. But i know, this is probably very difficult to implement. Because you also need a "back" button to navigate.

**Comment by jamesread** [comment]
I have thought about something like this, called "entities" - a single box that has multiple icons.

**Comment by jamesread** [comment]
Hey, I've just had some time to work on this, and wanted to share a development video that calls out some relevant changes. Does this fix the issue for you?

https://youtu.be/vWAD04Wpa8U

**Comment by TheRaven500** [comment]
Heya James, this looks really nice! :sunglasses: So many new features! Can't wait for it. But don't hurry, take your time! :wink:

**Comment by jamesread** [comment]
Hey @TheRaven500 , very keen for you to try out the 2024.02.27 release and see if the folders/directories work for you? 

https://docs.olivetin.app/folders.html

**Comment by TheRaven500** [comment]
Works! Thank you very much! :+1:
