### ISSUE TITLE
Timeout for textbox and drop-down arguments

### ISSUE THREAD

**Issue by Villantiqua** [OliveTin/OliveTin#153]
OliveTin is great, thanks!
I wonder whether the textbox and/or drop-down argument also have a time-out option. I can’t find it in the documentation.
Thanks!

**Comment by Villantiqua** [comment]
I answered my own question by trying. The answer is: yes, you can 🙂

**Comment by jamesread** [comment]
Hey @Villantiqua , glad that you answered your own question :-) Just curious, what do you mean be a time-out option?

**Comment by Villantiqua** [comment]
Hey,It’s in your own documentation:- actions:
  - title: My special action
    shell: sleep 5
    timeout: 10That’s the one I mean, and it also works in the dropdown arguments option.Thanks!Sent from my iPadOn 9 Aug 2023, at 22:39, James Read ***@***.***> wrote:﻿
Hey @Villantiqua , glad that you answered your own question :-) Just curious, what do you mean be a time-out option?

**Comment by jamesread** [comment]
Heya, yeah sure I know there is a timeout option for each action - but what do you mean about using a timeout as a "drop down option"? 

It shouldn't be possible to have an argument drop down select box to set the timeout.

Perhaps you could share the bit of your config file? I'd just like to understand what it is you wanted to do. Thanks!

**Comment by Villantiqua** [comment]
Hi James,Well, this part of my config.yaml just seems to work fine:- title: sync to Stack cloud  icon: "&#009072"  shell: "{{ message }}"  timeout: 900  arguments:      - name: message        choices:          - title: rsync Doks_local to Dox_Stack            value: sudo rsync --ignore-existing -azvh --exclude='.*' /mnt/SSD/Public/Docs/ /mnt/stack/QNAP/Dox/          - title: rsync music_local to music_Stack            value: sudo rsync --ignore-existing -azvh --exclude='.*' /mnt/SSD/mijnmedia/muziek/ /mnt/stack/QNAP/PicsMusic/Muziek/                      - title: rsync albums_local to albums_Stack            value: sudo rsync --ignore-existing -azvh --exclude='.*' /mnt/SSD/mijnmedia/albums/ /mnt/stack/QNAP/PicsMusic/albums/Sent from my iPadOn 10 Aug 2023, at 07:52, James Read ***@***.***> wrote:﻿
Heya, yeah sure I know there is a timeout option for each action - but what do you mean about using a timeout as a "drop down option"?
It shouldn't be possible to have an argument drop down select box to set the timeout.
Perhaps you could share the bit of your config file? I'd just like to understand what it is you wanted to do. Thanks!

**Comment by Villantiqua** [comment]
Sorry, this should have gone better, again in code:
`- title: sync to Stack cloud
  icon: "&#009072"
  shell: "{{ message }}"
  timeout: 900
  arguments:
      - name: message
        choices:
          - title: rsync Doks_local to Dox_Stack
            value: sudo rsync --ignore-existing -azvh --exclude='.*' /mnt/SSD/Public/Docs/ /mnt/stack/QNAP/Dox/

          - title: rsync music_local to music_Stack
            value: sudo rsync --ignore-existing -azvh --exclude='.*' /mnt/SSD/mijnmedia/muziek/ /mnt/stack/QNAP/PicsMusic/Muziek/
            
          - title: rsync albums_local to albums_Stack
            value: sudo rsync --ignore-existing -azvh --exclude='.*' /mnt/SSD/mijnmedia/albums/ /mnt/stack/QNAP/PicsMusic/albums/
  
`

**Comment by jamesread** [comment]
Okay so you're just using the timeout option, not related to a drop-down argument or anything :-) Glad you got what you needed!
