### ISSUE TITLE
Web UI keeping old config.yaml actions although config.yaml file has been updated.

### ISSUE THREAD

**Issue by djeinstine** [OliveTin/OliveTin#155]
**Describe the bug**
Web UI keeping old config.yaml actions although config.yaml file has been updated. The UI updates the first time the config yaml has changed, but keeps the old data in cache for subsequent changes to the file.

**To Reproduce**
Update the yaml file while olivetin container is running, i.e.:
1. Add an action
3. Remove an action
4. Add an action

**Expected behavior**
I would expect the UI to updated with each modification of the .yaml file

**Screenshots**
![image](https://github.com/OliveTin/OliveTin/assets/2105133/f827e613-b9fd-4524-a349-c372a06fcae2)

![image](https://github.com/OliveTin/OliveTin/assets/2105133/fb6672d7-3ebc-41f2-8fcf-bc36519d6064)

**Additional context**
I've refreshed olivetin multiple times after seeing the bug, however, that does not solve it. Only restarting the container completely solves the issue.

Edit: Also the stale actions keep the old .yaml configuration. So they are not empty. I.e. if I were to press the buttons that are not supposed to exist, they will perform the same shell action as if their configuration were in the file.

**Comment by jamesread** [comment]
Hey @djeinstine , thanks for reporting this issue - this should not happen.

From your screenshot I cannot quite tell what is "stale" though - what is it that is not being updated?

**Comment by djeinstine** [comment]
Hi. I guess I messed up the explanation. 

1. The syncthing, radarr and deluge actions where added at the start.
2. Radarr and Deluge were deleted in the config.yaml
3. Config.yaml only has Syncthing (as shown)
4. All three buttons still remain (with full functionality)

**Comment by jamesread** [comment]
The release last night contains a more robust method of reloading actions, and should be far more robust. Please checkout the 2024.05.27 release. 

I've tested this several times and believe it should now work as expected so I'm closing this issue, but please do reopen if you're still seeing problems.

**Comment by Vinnythetrue** [comment]
I am encountering the same issue with the 2024.09.16 version...
