### ISSUE TITLE
How to restart a docker container (plex), on a Windows host?

### ISSUE THREAD

**Issue by jbeck22** [OliveTin/OliveTin#157]
I installed OliveTin on my unRaid server as a docker container.  I created the "hello world" config.yaml file and the container starts...no issues there.

I wanted to add a button to restart my Plex Server but Plex runs on a different machine and is Windows based.  How do I call a PowerShell script from within OliveTin on a different machine?

**Comment by mcmiv413** [comment]
@jbeck22 My suggestion here would be one of a few different approaches.

- I would either setup ssh on the windows system and then run the command via ssh https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration

- Or you could setup a scheduled task to trigger a script that looks for a file, your action could then generate this file on a network share to be picked up.  This would not be an immediate trigger, but may be the easiest. https://superuser.com/questions/226828/how-to-monitor-a-folder-and-trigger-a-command-line-action-when-a-file-is-created 

- Or you could use some sort of messaging que where you action submits the message and on the windows side it is subscribed to the message to perform the action. https://jackgruber.github.io/2019-06-05-ps-mqtt/

I'm sure there are other ways and there are pros and cons to each of the methods I listed.

**Comment by jamesread** [comment]
Hey @jbeck22 , on top of the suggestions from @mcmiv413 , there is actually a very simple way - by setting the DOCKER_HOST environment variable. Here is an example in OliveTin config;

````
actions: 
  - name: Restart container on Windows
    shell: DOCKER_HOST=tcp://192.168.0.1:2375 docker restart plex
    icon: poop
````

**Comment by jamesread** [comment]
Closing as no comments in 3 mknths.
