### ISSUE TITLE
Add notification support

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [OliveTin/OliveTin#158]
**Is your feature request related to a problem? Please describe.**
If a command is set on schedule using cron, I would like to have the option to view the output via an email in case it fails OR even if it succeeds. This reduces the burden of having to go check logs & acts as a reminder for the cron command itself.

**Describe the solution you'd like**
A way to define SMTP credentials which allow sending emails alongwith an option of when to send the email - always, on-fail etc.

**Describe alternatives you've considered**
Currently using OMV's built in scheduled tasks to achieve this, but would like to move it all to OliveTin.

**Comment by jamesread** [comment]
Hey @Gandalf-the-Blue , I've just managed to find some time to get this done, and I think it's pretty elegant :-) I decided to call the option "shellAfterCommand", so the config looks like this; 

```
  # This will run a simple script that you create.
- title: Run backup script
  shell: /opt/backupScript.sh
  shellAfterCompleted: "apprise -t 'Notification: Backup script completed' -b 'The backup script completed with code {{ exitCode}}. The log is: \n {{ stdout }} '"
  maxConcurrent: 1
  icon: backup
```

This example shows the excellent apprise being called on the command line for notifications (https://github.com/caronc/apprise), but do you think this feature in general will work for you?

**Comment by Gandalf-the-Blue** [comment]
That was quite quick @jamesread . Thanks for implementing this.
I guess I'm not hosting Apprise on my server
