### ISSUE TITLE
Safari on Mac/iPhone does not support createElement with options

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#17]
**Describe the bug**
https://caniuse.com/mdn-api_document_createelementns_options_parameter

![image](https://user-images.githubusercontent.com/2025715/127302911-98fb2013-42e1-40e5-a55e-8220fb88a8a7.png)

**To Reproduce**
Tried on Safari 13.1. 

**Approach**
- [x] Will look into when Safari will be supporting this. 
- [x] If not, will look into alternatives. 
- [x] Port OliveTin's "Customized Built-in Elements" to "Autonomous Custom Elements". 

**Known workaround**;
Use Firefox or Chrome on Mac until this is fixed with Safari.

**Comment by jamesread** [comment]
> Will look into when Safari will be supporting this.

So, it looks like the Safari developers don't want to support Customized Builtin Elements via the CE standard - https://bugs.webkit.org/show_bug.cgi?id=182671 , (but they so support Autonomous Custom Elements). Given that the upstream issue discussion did not go well, it looks like "just waiting this one out" won't see support in Safari for a while (if at all).

> If not, will look into alternatives.

With the information above, the options that I see are; 

1) Convert OliveTin's custom elements to Autonomous Custom Elements. The **advantage** is that it's well supported across most browsers, but the **disadvantage** is that at the moment, inheriting from `<button>` gives us a lot of useful accessibility benefits. 
2) Drop custom elements entirely. This also would solve the issue, but the **disadvantage** is that the code is more bloated, legacy. I believe in the progressive web, so "downgrading" here isn't a good option.
3) Add a polyfill. For the same reason as above, the **disadvantage** of polyfilling in my personal view, holds the web back, and makes the codebase bloated with additional dependencies.
4) Feature-detect & workaround. Again, the **disadvantage** is code-bloat. 
5) Choose not to support Safari. This seems like it would affect 3-5% of users, according to https://caniuse.com/custom-elementsv1 . There is a workaround though (using Firefox or Chrome). 

On considering the above, **Option 1 - Convert OliveTin's custom elements to Autonomous Custom Elements** seems to be the best way forward. I aways liked to try and support all browsers, even if they cannot all get along together :-) To overcome the accessibility issues, the custom element template can nest a `<button>` element. 

This fix for this should be included in the next release of OliveTin.

**Comment by ScrumpyJack** [comment]
Looking forward to this fix

**Comment by jamesread** [comment]
Quick note, the code for this feature should now be complete in the safari-create-element branch, as of commit 8ecaf33b1acfbef2ff9eb7504ccad42387217a90

https://github.com/OliveTin/OliveTin/tree/safari-create-element

This is now shortly going to be merged into the main branch after a bit of extra testing. Really hoping to get this released in the next few days.

**Comment by jamesread** [comment]
This was fixed in the 2021-11-19 release.

**Comment by AlphaJack** [comment]
@jamesread I am unable to view OliveTin on iOS 12.5.5

Desktop browser (portrait mode to simulate what I should see on mobile):
```
192.168.1.1 - - [27/Jan/2022:17:08:21 +0100] "GET /olivetin/ HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
192.168.1.1 - - [27/Jan/2022:17:08:22 +0100] "GET /olivetin/webUiSettings.json HTTP/2.0" 200 100 "https://example.org/" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
```

---

Mobile browse:

```
192.168.1.2 - - [27/Jan/2022:17:08:50 +0100] "GET /olivetin/ HTTP/2.0" 200 1290 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 12_5_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/36.0  Mobile/15E148 Safari/605.1.15"
```





![firefox-gecko](https://user-images.githubusercontent.com/19962243/151396108-586d3c25-5028-4f7c-9990-3369ca985e40.png)

Web server logs:



![firefox-webkit](https://user-images.githubusercontent.com/19962243/151396115-41e9514b-9ae3-4fde-b4d6-608149dffceb.jpg)
