### ISSUE TITLE
Websocket support for reverse proxies

### ISSUE THREAD

**Issue by flammable** [OliveTin/OliveTin#173]
**What seems to be the problem?!**

Thanks for the new version! After installing, I noticed websocket support is now included. At the bottom of the page, I see the message:

`Server connection: disconnected, trying to reconnect...`

I assume that's related to websockets not being able to pass through my reverse proxy? If so, any idea what I'd need to do to allow this traffic to pass through?

**Can you provide a sosreport?**

```
level="info" msg="\n### SOSREPORT START (copy all text to SOSREPORT END)\n# Build: \ncommit: \"9522e25\"\nversion: 2023.10.09\ndate: \"2023-10-09T22:11:04Z\"\n\n# Runtime:\nos: linux\nosreleaseprettyname: PRETTY_NAME=\"Fedora Linux 36 (Container Image)\"\narch: amd64\nincontainer: true\nlastbrowseruseragent: \"\"\n\n# Config:\ncountofactions: 7\nloglevel: INFO\n\n### SOSREPORT END  (copy all text from SOSREPORT START)\n"
```

**What package/file/container did you use to install OliveTin?**

`ghcr.io/olivetin/olivetin:latest` (2023.10.09)

**Your config.yaml**

```
# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

# Toggle whether to check for updates at all
checkForUpdates: false

# Toggle to show if an update is available in the footer
showNewVersions: false

# Actions (buttons) to show up on the WebUI:
actions:
<snip>
```

**OliveTin logs**

Besides me running actions, here's all that's in my Docker logs:

```
level="info" msg="OliveTin initializing" commit="9522e25" date="2023-10-09T22:11:04Z" version="2023.10.09"
level="debug" msg="Value of -configdir flag" value="."
level="info" msg="Setting log level to info"
level="info" msg="Init complete"
level="info" msg="OliveTin started" configDir="/config"
level="info" msg="Starting REST API" address="localhost:1339"
level="info" msg="Startup action" action="Customize OliveTin"
level="info" msg="Starting WebUI server" address="localhost:1340"
level="info" msg="Found the webui directory" dir="/var/www/olivetin/"
```

**Screenshot of WebDeveloper console logs**

I'm not sure if this is relevant, but if it is, please let me know!

**Anything else?**

I'm using SWAG as my reverse proxy, which uses nginx, but I'm pretty sure I can adapt anything that'd work. Thanks for taking a look at this, and also for OliveTin! 😄

**Comment by jamesread** [comment]
Hey @flammable , yeah, I'm seeing some reports of this being broken with nginx with this latest release. I'm sorry about that :-(

Could you post your nginx config, and most importantly the WebDeveloper console logs? I'm expecting to see some CONNECTION CLOSED or similar javascript errors that.

**Comment by flammable** [comment]
Oh, no worries! Everything else works great - I just don't get realtime notifications when my task has completed. Luckily, that's not a huge issue for me, because I can just go see if my task has completed outside of OliveTin.

Here's the reverse proxy config I made for using OliveTin with SWAG:

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name olivetin.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    #include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    include /config/nginx/authentik-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        #include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app olivetin;
        set $upstream_port 1337;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```

I'm not sure if it matters, but I'm securing OliveTin by putting it behind Authentik, which provides SSO and MFA.

I think I grabbed the correct WebDeveloper console logs, but let me know if you're looking for an increased logging level, or something else:

```
websocket.js:21 WebSocket connection to 'wss://olivetin.mydomain.com/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404
reconnectWebsocket @ websocket.js:21
checkWebsocketConnection @ websocket.js:7
refreshLoop @ main.js:35
(anonymous) @ main.js:115
websocket.js:68 Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
websocketOnError @ websocket.js:68
error (async)
reconnectWebsocket @ websocket.js:25
checkWebsocketConnection @ websocket.js:7
refreshLoop @ main.js:35
(anonymous) @ main.js:115
Promise.then (async)
main @ main.js:110
(anonymous) @ main.js:123
websocket.js:21 WebSocket connection to 'wss://olivetin.mydomain.com/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404
reconnectWebsocket @ websocket.js:21
checkWebsocketConnection @ websocket.js:7
refreshLoop @ main.js:35
websocketOnError @ websocket.js:67
websocket.js:68 Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
websocketOnError @ websocket.js:68
error (async)
reconnectWebsocket @ websocket.js:25
checkWebsocketConnection @ websocket.js:7
refreshLoop @ main.js:35
websocketOnError @ websocket.js:67
error (async)
reconnectWebsocket @ websocket.js:25
checkWebsocketConnection @ websocket.js:7
refreshLoop @ main.js:35
(anonymous) @ main.js:115
Promise.then (async)
main @ main.js:110
(anonymous) @ main.js:123
```

Also, I had to set `externalRestAddress` to my full URL in my config.yaml file to be able to generate the sosreport, so maybe this might require something similar?

**Comment by Typhonragewind** [comment]
Same issue here with nginx (SWAG)

**Comment by jamesread** [comment]
So, this is better described in #177 , but there were two bugs in the websocket implementation, I'm really sorry about that :-(

**Comment by jamesread** [comment]
@flammable @Typhonragewind could you check the `2023.10.24` release please, being sure to set the Upgrade and Connection headers as seen in this example here; https://docs.olivetin.app/nginx-dns.html

**Comment by jamesread** [comment]
- [ ] Document websocket configuration for reverse proxy: Apache
- [ ] Document websocket configuration for reverse proxy: haproxy
- [ ] Document websocket configuration for reverse proxy: Caddy
- [ ] Document websocket configuration for reverse proxy: Traefik

**Comment by jamesread** [comment]
- [ ] Document websocket configuration for reverse proxy: Apache
- [ ] Document websocket configuration for reverse proxy: haproxy
- [ ] Document websocket configuration for reverse proxy: Caddy
- [ ] Document websocket configuration for reverse proxy: Traefik

**Comment by ManOki** [comment]
Hi, I've also setup a reverse proxy but websocket is not working. I'm on version **2023.12.17** (latest docker) and keyword "Websocket" is marked red in footer.

Because I host several services on that web server, each of them has its own path/directory/webroot, e.g., https://my-server-ip.com/olivetin/. While this is working fine for regular html+rest, OliveTin tries to connect to websocket via https://my-server-ip.com/websocket/, not https://my-server-ip.com/olivetin/websocket/. I debugged this via Firefox Dev Console.

My config includes `externalRestAddress: https://my-server-ip.com/olivetin` but this have no impact on websocket connection.

Greets, ManOki

**Comment by jamesread** [comment]
Hey @ManOki , I really need to document the websockey reverse proxy - the current documentation is wrong because it won't work with the new websocket. 

Which proxy do you use?

**Comment by jamesread** [comment]
I remember I updated the nginx proxy docs; 

https://docs.olivetin.app/nginx-dns.html

**Comment by ManOki** [comment]
I use apache. Besides that, you already provide the option to specifically define the external address, but this is not taken into account for the websocket address. I like this explicit option much better than fiddling with reverse proxy + rewriting configuration, where you might miss a deeply hidden web address path.

Think of 2 parallel instances of OliveTin for one reverse proxy: How should the proxy decide where to pass a `/websocket` request?

**Comment by jamesread** [comment]
@ManOki - I've just tested with apache and updated the docs here, using ModRewrite I got a stable working websocket connection with apache.

https://docs.olivetin.app/apache-dns.html

Could you test and let me know if this works OK?

**Comment by flammable** [comment]
@ManOki If you can, switch to subdomains instead of subfolders. I had a lot of trouble in the past with using subfolders, and subdomains aren't a huge amount of work to set up. SWAG has some great documentation on how to use a DNS service that supports wildcard CNAMEs.

**Comment by jamesread** [comment]
@flammable is absolutely right - while I've put a good amount of care into making sure OliveTin works with subdirectories, this isn't really a long term solution, it's fragile and error prone.

**Comment by jamesread** [comment]
I'm going to close this now, as this should now be much better documented with examples now that websocket support has been introduced. 

https://docs.olivetin.app/proxy-guide.html#_handling_websockets

If anybody is reading this and is having problems with configuring their proxy with websocket support, please feel free to open an issue or jump into the Discord chat and we'll happily help :-)
