### ISSUE TITLE
Save execution logs

### ISSUE THREAD

**Issue by accforgithubtest** [OliveTin/OliveTin#174]
**Is your feature request related to a problem? Please describe.**
Persist execution logs for all actions (manual, cron, onstartup, etc) to a log file so it can be used later (review / log analysis using other tools, etc). Neat if can also be displayed on the UI after a restart.

**Describe the solution you'd like**
A log file using a common standard format stores the logs to a log file in the same directory as the config file (for docker volume simplicity sake, it can also be a different volume if need be). 
Probably will need log rotation & automated clean up after x days - both of which can be specified via environment variables.

**Describe alternatives you've considered**
Pls suggest if there are alternatives already available. Apologies if I have missed something that exists already.

**Additional context**
Right now all the previous executions log are lost once the container restarts.

**Comment by jamesread** [comment]
heh, I did wonder when this request would be raised :-) It means I need to implement a whole log handling solution! 

It does make sense though, thanks for the feature request. I'd like to fix some other stuff first and get the issues list down a bit more before I take this on - as it's a fairly chunky feature.

For anyone else reading this, +1ing the first post here with an Emoji is helpful for me to understand how many people want this feature.

**Comment by jamesread** [comment]
#147 has a good idea to specifically the log filename on a per action basis, like `resultFile`.

**Comment by jamesread** [comment]
Okay, I've beeb avoiding this for quite a while because I was worried about all the log handling, but actually if I just write the log file on competition it solves a hell of a lot of problems and is very easy. 

The code doesn't yet load logs from disk at startup, but I'm going go handle that as a separate issue.

**Comment by jamesread** [comment]
No feedback received, but got some :heart:'s so assume that is good enough after a month :-) Closing.

**Comment by joaquinTiendamia** [comment]
@jamesread  Hey James! How are you? First of all, I want to thank you for OliveTin; it's a very helpful application for my work.

I have an issue with the logs. I have the configuration set up correctly, and the logs are being saved on my server, but every time I refresh the web interface, I can no longer see them.

**Comment by jamesread** [comment]
> @jamesread Hey James! How are you? First of all, I want to thank you for OliveTin; it's a very helpful application for my work.
> 
> I have an issue with the logs. I have the configuration set up correctly, and the logs are being saved on my server, but every time I refresh the web interface, I can no longer see them.

Heya, please open a new issue. I'm more than happy to help you fix this, just I won't see notifications for comments against closed issues! :-)
