### ISSUE TITLE
Native packages (.rpm, .deb) should not run as root! 

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#18]
**Is your feature request related to a problem? Please describe.**
root = bad, least-privilege = good.

**Describe the solution you'd like**
Probably should hand-bake the .rpm, .deb packages, even better would be getting them accepted in the native distributions.

**Comment by ToeiRei** [comment]
Why not just dropping privileges? Linux Caps could do the trick by detecting if we run as root (without --i-am-sure-i-want-to-run-as-root) - that way we can still use ports <1024

my crude c attempt would be something like that
```
if (getuid() == 0) {
 /* process is running as root, drop privileges */
 if (setgid(groupid) != 0)
 fatal("setgid: Unable to drop group privileges: %s", strerror(errno));
 if (setuid(userid) != 0)
 fatal("setuid: Unable to drop user privileges: %S", strerror(errno));
 }
 ```
