### ISSUE TITLE
Error getting webui settings

### ISSUE THREAD

**Issue by accforgithubtest** [OliveTin/OliveTin#184]
**Describe the bug**
A red banner on the application with below error message 
```
Error getting webui settings
TypeError: document.querySelector(...) is null
[fetch-webui-settings error in OliveTin Documentation](http://docs.olivetin.app/err-fetch-webui-settings.html)
```

**To Reproduce**
Update from 2023.10.12 to 2023.10.25

**Screenshots**

**Additional context**

1. Did not see this issue with 2023.10.12 (and earlier).

1. As mentioned in the [documentation](https://docs.olivetin.app/err-fetch-webui-settings.html), I have checked the url by accessing - https://olivetin.local.host/webUiSettings.json and see the below json 
```
{"Rest":"./api/","ThemeName":"","ShowFooter":false,"ShowNavigation":true,"ShowNewVersions":false,"AvailableVersion":"","CurrentVersion":"2023.10.25","PageTitle":"OliveTin"}
```

1. Additional info - Reverse proxy is Caddy, and is set up to be subdomain based - olivetin.local.host, using self-signed certificates.

**Comment by accforgithubtest** [comment]
A restart of the host machine fixed the issue for me !

**Comment by jamesread** [comment]
Ah, this is most likely old JavaScript cached in your browser that didn't work after a version upgrade. Ctrl+F5 would probably have fix it too!
