### ISSUE TITLE
Want to include sshpass when publishing docker images

### ISSUE THREAD

**Issue by feixu0530** [OliveTin/OliveTin#185]
Since I set up an automatic docker image update, every time OliveTin posts a new docker image, some remote command buttons on my page will fail due to the lack of built-in sshpass. I think the best part of OliveTin's Docker image is the ability to execute a command with a single button. So sshpass is preinstalled directly in the image, which is very helpful.

**Comment by jamesread** [comment]
Hey @feixu0530 , checkout this page of the docs for an easy and reliable way to do that; https://docs.olivetin.app/exec-startup.html#dnf-startup

**Comment by feixu0530** [comment]
In fact, I did. But the efficiency is too low. I wonder if it is because microdnf is not used much in China. I install sshpass and wait for microdnf update -y && microdnf install sshpass -y. This command is complete. It takes a long time. If docker's image can be changed to ubuntu, using apt, I think it will also be very helpful for me.

**Comment by jamesread** [comment]
Hey @feixu0530 , are you saying it takes a long time? It should take less than 30s, and only execute fully when new versions are published?

**Comment by feixu0530** [comment]
Yes, I execute this command :microdnf update -y && microdnf install sshpass -y. Each session will take 5-10 minutes. Because microdnf is really not a commonly used package manager, at least in China. 
This requirement is due to the recent update of two successive versions. I think the built-in sshpass as a remote execution feature is really useful.

**Comment by feixu0530** [comment]
Or can the initial image packaged with docker image use Ubuntu? Because the speed of apt source in China is still satisfactory.

**Comment by jamesread** [comment]
@feixu0530 , moving to Ubuntu isn't going to happen for the official images - because building fedora has many advantages. 

How long does it really take on Fedora to install the package?

**Comment by feixu0530** [comment]
My reality is 5-10 minutes。

**Comment by jamesread** [comment]
Okay, why don't you just use ssh keys?

**Comment by feixu0530** [comment]
Because the configuration process is more troublesome. It's all on the Intranet. Don't worry sshpass security.

**Comment by jamesread** [comment]
I'm sorry, I'm not going to preinstall sshpass, it's insecure, and the workaround only takes you 5 minutes - to install it yourself or use private keys.
