### ISSUE TITLE
Cannot update the timezone of the docker container

### ISSUE THREAD

**Issue by rafapirotto** [OliveTin/OliveTin#193]
**What seems to be the problem?!**

I can't seem to override the timezone using the TZ env variable. I think it may have to do with the fact that the "tzdata" dependency is not used in the docker image?

**Can you provide a sosreport?**

N/A

**What package/file/container did you use to install OliveTin?**

Container from Dockerhub with the latest tag

**Your config.yaml**

N/A

**OliveTin logs**

N/A

**Anything else?**

N/A

**Comment by jamesread** [comment]
Hey there, I figured out how to do this now with OliveTin's fedora-minimal inage. I've documented it here

 https://docs.olivetin.app/timezone.html

Let me know if yiu have any issues!
