### ISSUE TITLE
Dialog width too large on mobile

### ISSUE THREAD

**Issue by lukkigi** [OliveTin/OliveTin#197]
Thanks for creating this tool. It's been really helpful! 

**Describe the bug**
When opening OliveTin on my phone and using the dropdown argument, I can't see the start button that is supposed to be clicked.

<img width="233" alt="Screenshot 2023-12-05 at 18 20 21" src="https://github.com/OliveTin/OliveTin/assets/5468186/baeee338-d0cf-4fc0-8d3b-8431fe668006">

**Comment by jamesread** [comment]
Thanks @lukkigi , that's a silly mistake. Just pushed a fix for it and it'll be included in the next release.

**Comment by jamesread** [comment]
@lukkigi Could you test on the 2023.12.20 release for me please? You will probably need to Ctrl + F5 in your browser / clear mobile cache to get the updated stylesheet.

**Comment by lukkigi** [comment]
@jamesread working great again, thank you!
