### ISSUE TITLE
Make "www" dir path configurable

### ISSUE THREAD

**Issue by hydrargyrum** [OliveTin/OliveTin#198]
**Is your feature request related to a problem? Please describe.**
I want to run olivetin as an unprivileged user and have no write access to /var/www.

**Describe the solution you'd like**
Be able to configure the path. Probably in command-line (like `--webui /var/www/olivetin` by default), but could also be in config file or in environment variable.

**Comment by jamesread** [comment]
Heya, it is already configurable, it's just undocumented! :-) 

```yaml
webUiDir: /home/bob/olivetin/webui
```

Obviously you will need to place the webUi files in that directory.

**Comment by hydrargyrum** [comment]
Woah, thanks, I will test that!

**Comment by jamesread** [comment]
@hydrargyrum , just checking, I presume it worked OK for you?
