### ISSUE TITLE
Update-check website doesn't exist

### ISSUE THREAD

**Issue by tim-durrant** [OliveTin/OliveTin#20]
Update Check Failed
This domain seems to have disappeared?  http://update-check.olivetin.app

**Comment by jamesread** [comment]
Hey @tim-durrant , thanks for taking the time to report this. 

I had been messing around on the server that hosts the olivetin-updates virtual machine, and didn't realize the virtual machine had shutdown temporarily, it's back up now. 

I've added a couple of monitoring checks to my personal Grafana instance to keep an eye on it going forward. Thanks for the heads up. 

Note that visiting the URL in a browser will not work, as the root domain (olivetin.app) has HSTS enabled (enforce TLS). The update check is deliberately over HTTP and not HTTPS for transparency - so people can verify that the update check does only what it says it does. 

I don't think there any more follow up needed here at the moment, so I'd look to close this issue if you are happy with that description?

**Comment by jamesread** [comment]
I've added a note in the documentation that explains a bit more about HSTS / visiting via a browser. 

https://docs.olivetin.app/update-tracking.html#hsts

I don't think there is much else that is needed here. If you'd like any more information (or anybody else does), please re-open this issue or open a new one. 

Thanks for your time and interest in OliveTin :-)
