### ISSUE TITLE
execOnCron expected exactly 6 fields, found 5

### ISSUE THREAD

**Issue by meerkatzenwildschein** [OliveTin/OliveTin#202]
The cron configuration listed as an example in the documentation at https://docs.olivetin.app/exec-cron.html causes the following error.

`schedule error" action="Say goodbye" cronError="expected exactly 6 fields, found 5: [*/5 * * * *]"`

With the following cron the execution works as expected every 5 minutes. `"0 */5 * * * *"`. The cron implementation used with OliveTin probably supports seconds and therefore differs from the standard Linux cron. 

It may be helpful for others to supplement the documentation accordingly.

**Comment by jamesread** [comment]
Hey @meerkatzenwildschein , I'm really sorry that you've hit this, I'm not sure why I don't have both an example in the default config, or this documented properly.

I'll get to work on both.

**Comment by jamesread** [comment]
I decided to make the default cron format support the most popular format that everyone typically knows - without seconds (5 fields), and make an option in the config to switch formats (`cronSupportForSeconds`), which if set to true, changes the cron format to 6 fields - the first of all being seconds. There might be some people that rely on the seconds support for scripts or something.

This is now documented here; https://docs.olivetin.app/exec-cron.html
