### ISSUE TITLE
Disable the "Actions" and "Logs" buttons

### ISSUE THREAD

**Issue by efelon** [OliveTin/OliveTin#21]
**Is your feature request related to a problem? Please describe.**
For non tech. people to provide as few buttons as possible.

**Describe the solution you'd like**
It would be nice to disable the "Actions" and "Logs" buttons on the top of the page to make it as clean as possible.
In `config.yaml` something like `navigation: disable`.

**Additional context**
I equipped my parents in law with a raspberry running kodi. Every now and then kodi hangs and the only option for them on their own is to power cycle the pi. The more elegant solution would be to just restart the service, for which I haven't found an elegant solution for non technical people until I stumbled upon OliveTin. This will be a website-link on their phones open the site with only one button "Restart Kodi".

**Comment by jamesread** [comment]
Hey, just got this working this morning. The buttons are mearly hidden from the browser - so this appropriate as a security control, but will certainly be enough for just rendering a "simpler" interface.

![image](https://user-images.githubusercontent.com/2025715/137577350-aa00e76d-a418-48df-86af-5bafafaab596.png)

I think this is very likely to make the next release, but it needs an integration test now.

**Comment by efelon** [comment]
@jamesread thank you very much for your work. But would you mind elaborate how to actually hide it. I was not able to figure it out by myself after looking at the documentation, your commit or the config.yaml example.

**Comment by ashleycawley** [comment]
Hey @efelon my response isn't necessarily related to OliveTin, but I had a thought: for your parents in law's situation what might be even easier for them (if they've none techy) is to wire up a simple button. So they've got a physical button they just present which initiates a bash or python script which reboots the Pi. There seems to be a few examples of others who have done that floating around online. Thought it might be even easier for them than navigating to a particular page/IP on their laptop or mobile. :+1:

**Comment by efelon** [comment]
@ashleycawley thanks for the suggestion. I actually haven't thought about that. Until now I have used rpis only for "server" purposes. The advantage of OliveTin is, that they need to get up from the couch ;) and that I can also execute it very quickly. But a hardware button would be a great fallback anyway.

**Comment by ashleycawley** [comment]
No problem, I just know some people prefer a more "analogue" approach shall we say. It'd be cool if a hardware button elegantly restarted the service for them. Failing that OliveTin!

**Comment by jamesread** [comment]
@efelon , Sorry for the delay in getting back to you. Your config should include this;

````
hideNavigation: true
````

**Comment by jamesread** [comment]
@efelon This is now fully documented here; https://docs.olivetin.app/hide-nav.html 

From your :tada: emoji I am going to assume this worked for you :-) If not please feel free to re-open this issue.
