### ISSUE TITLE
Link to latest version for downloading

### ISSUE THREAD

**Issue by TheRaven500** [OliveTin/OliveTin#211]
Is it possible to offer a link to latest version for downloading?
Actual this is the link for latest version (armv6 in this example):
https://github.com/OliveTin/OliveTin/releases/download/2023.12.21/OliveTin_linux_armv6.deb
So what about something like this:
https://github.com/OliveTin/OliveTin/releases/download/latest/OliveTin_linux_armv6.deb
Which points always to latest version.

This way it is easier to update to latest version.
What do you think about this?

**Comment by jamesread** [comment]
Heya, 

This is a really good idea, I started working on a page in the release notes that I could link to, but I think I was making it too overcomplicated. 

Probably just to link to the current releases page in the docs.

**Comment by TheRaven500** [comment]
Try to keep it simple! ;-) With a link to the latest version it is much easier to update because you can write a simple script (something like "wget https://latest.deb;dpkg -i latest.deb". Then just run the script and you are on latest release.

**Comment by jamesread** [comment]
Ah you can do that bit already - these are the direct links to the packages that always link to the latest versions; 

https://docs.olivetin.app/choose-package.html

**Comment by TheRaven500** [comment]
Ah, then this "issue" is fixed! :wink:
