### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon socket

### ISSUE THREAD

**Issue by saschabrockel** [OliveTin/OliveTin#215]
Experienced docker user and I'm confused why it's not working with OliveTin. No problem doing it with portainer or other tools.

The logs
`level="info" msg="Action finished" actionTitle="Restart Plex" exit="1" stderr="Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/plex/restart\": dial unix /var/run/docker.sock: connect: permission denied\n" stdout="" timedOut="false"`

My docker run command:
```
docker run
  -d
  --name='OliveTin'
  --net='unraid'
  -e TZ="Europe/Berlin"
  -e HOST_CONTAINERNAME="OliveTin"
  -p '1337:1337/tcp'
  -v '/mnt/cache/appdata/olivetin':'/config':'rw'
  -v '/var/run/docker.sock':'/var/run/docker.sock':'rw'
  --privileged 'jamesread/olivetin:latest'
```

**Comment by jamesread** [comment]
Heya, I'm not entirely sure why that would be the case, but fundamentally OliveTin doesn't do anything magic with docker - if that's what you're doing with other containers, it should work in theory. 

Does it work from a shell inside the OliveTin container?

**Comment by jamesread** [comment]
Note about timezone: https://docs.olivetin.app/timezone.html

**Comment by saschabrockel** [comment]
That's also what I thought. How to test in the shell? Do you mean the command?

**Comment by jamesread** [comment]
Yeah, so from your container host, something like; `docker exec -it myolivetincontainer /bin/bash`, then try running things like `docker ps`. 

The UID of the OliveTin user is 1000 inside the container, I wonder if that user needs to be in you uid/gid map - what OS are you running on your container host? As a workaround, try running your `docker create` command with `--user 0` or `--user root`

**Comment by saschabrockel** [comment]
Actually permissions issue. It works when I run `docker exec` with root rights. My system is unRAID. I tried PUID and PGID but they don't seem to apply.

**Comment by jamesread** [comment]
Okay cool, if it worked with `docker exec --user 0 ...` then it's just that the default OliveTin user (1000) isn't in your host's PID/GID map. Don't change that, as it's confusing as hell, instead just change the user OliveTin run's as. 

As you say, PUID / PGID don't work with the OliveTin container image, that's documented with an explainer here; https://docs.olivetin.app/no-puid-pgid.html

So, recreate the container with `docker create --user ...` etc - just adding --user to the command in your first comment on this issue.

**Comment by saschabrockel** [comment]
Yeah, I did it with `-u root` and it works now. Might be a good idea to add it to the docs if somebody stumbles over the same problem.

**Comment by jamesread** [comment]
Heya @saschabrockel ; I've just pushed a note into the docs here, under the "Note" part of that page: https://docs.olivetin.app/action-container-control.html#_setup_if_running_inside_a_container

Do you think that would have helped you, and will help others in the future?

**Comment by saschabrockel** [comment]
Yeah, this note is perfect! Thank you for the quick help and this good piece of software!
