### ISSUE TITLE
OliveTin won't start on Ubuntu 23.10, it just exits immediately with no error

### ISSUE THREAD

**Issue by ryanovas** [OliveTin/OliveTin#221]
**Describe the bug**
I downloaded [OliveTin_linux_amd64.deb](https://github.com/OliveTin/OliveTin/releases/latest/download/OliveTin_linux_amd64.deb) from the docs and installed it with `dpkg` then enabled the service as described [in the install docs](https://docs.olivetin.app/install-linuxpackage.html).

No matter what I do it just exits. If I try to run it with systemctl I get these logs:

```
Jan 31 22:07:40 mobile-lab systemd[1]: Started OliveTin.service - OliveTin.
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="info" msg="OliveTin initializing" commit="6b0e414" date="2023-12-21T01:26:17Z" version="2023.12.21"
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="debug" msg="Value of -configdir flag" value="."
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="info" msg="Setting log level to info"
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="info" msg="OliveTin initialization complete"
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="info" msg="OliveTin started" configDir="/etc/OliveTin"
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="info" msg="Installation ID" content="${my-install-id}" from="/etc/OliveTin/installation-id.txt"
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="info" msg="Starting REST API" address="localhost:1339"
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="info" msg="Starting single HTTP frontend" address="0.0.0.0:1337"
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="info" msg="Starting WebUI server" address="localhost:1340"
Jan 31 22:07:40 mobile-lab OliveTin[2679466]: level="info" msg="Found the webui directory" dir="/var/www/olivetin/"
Jan 31 22:07:40 mobile-lab systemd[1]: OliveTin.service: Deactivated successfully.
Jan 31 22:07:40 mobile-lab systemd[1]: OliveTin.service: Scheduled restart job, restart counter is at 5.
Jan 31 22:07:40 mobile-lab systemd[1]: Stopped OliveTin.service - OliveTin.
Jan 31 22:07:40 mobile-lab systemd[1]: OliveTin.service: Start request repeated too quickly.
Jan 31 22:07:40 mobile-lab systemd[1]: OliveTin.service: Failed with result 'start-limit-hit'.
Jan 31 22:07:40 mobile-lab systemd[1]: Failed to start OliveTin.service - OliveTin.
```
 If I run it manually I get:

```
INFO OliveTin initializing                         commit="6b0e414" date="2023-12-21T01:26:17Z" version="2023.12.21"
DEBU Value of -configdir flag                      value="."
INFO Setting log level to info                    
INFO OliveTin initialization complete             
INFO OliveTin started                              configDir="/etc/OliveTin"
INFO Starting REST API                             address="localhost:1339"
INFO Installation ID                               content="492552dd-8f87-4ccd-a744-7729af874907" from="/etc/OliveTin/installation-id.txt"
INFO Starting single HTTP frontend                 address="0.0.0.0:1337"
INFO Starting WebUI server                         address="localhost:1340"
```

Then it exits.

If I set the log level to DEBUG it's all the same logs + it outputs the config. I am using the exact same config it came with, and I also tried the one in the main README.

I keep reading all this praise for OliveTin and wanted to try it but nothing I do seems to get it to actually start. I also can't seem to find this issue anywhere else.

**To Reproduce**
1. Install the package with dpkg from the link above on Ubuntu 23.10
2. Enable the service
3. Start the service

**Comment by jamesread** [comment]
Hey @ryanovas , thanks so for reporting this, and I'm really sorry that you've hit this issue. Something sounds strange here and doesn't make sense. 

OliveTin won't start without a config, but it should clearly log that it doesn't have a config to help people identify why it's exiting - the .deb should come with a sample config anyway in /etc/OliveTin

Hmm, let's get some more info: 

1. Can you run `md5sum /etc/OliveTin/*` for me please and share the output? 
2. If you run just `journalctl`, do you see anything else relevant about OliveTin getting killed? 
3. Is this a fresh Ubuntu 23.10 install, or do you jabe anything else configured, any non-defailt security settings? 

Jusy thinking things we can probably rule out; 

Ubuntu 23.10 should be fine, it's starting uo at least so it's not a library issue or anything. I can't imagine it's because you're running out of ram on amd64, and it's getting killed in the background or anything, so not sure - but we'll figure it out - it's probably something simple! 

You said you were reading lots of praise for OliveTin, do you mind me asking you heard about it? It's exciting for me to hear how people use OliveTin :-)

**Comment by jamesread** [comment]
Just to add, I tested inside a clean 1ubuntu:23.101 container and it works just fine;

```
user@host: docker run -it ubuntu:23.10 /bin/bash
user@container: apt-get update; apt-get install wget; wget https://github.com/OliveTin/OliveTin/releases/latest/download/OliveTin_linux_amd64.deb
user@container: dpkg -i OliveTin_linux_amd64.deb
user@container: OliveTin
INFO OliveTin initializing                         commit="0c19ba5" date="2024-01-27T23:43:30Z" version="2024.02.01"
DEBU Value of -configdir flag                      value="."
INFO Setting log level to info
INFO OliveTin initialization complete
INFO OliveTin started                              configDir="/etc/OliveTin"
INFO Starting REST API                             address="localhost:1339"
INFO Starting WebUI server                         address="localhost:1340"
INFO Found the webui directory                     dir="/var/www/olivetin/"
INFO Installation ID                               content="a786afcd-685b-4938-859e-dda61a37f98f" from="/etc/OliveTin/installation-id.txt"
INFO Starting single HTTP frontend                 address="0.0.0.0:1337"
INFO Update check complete                         NewVersion="none"
<normal startup, doens't exit>
```

**Comment by jamesread** [comment]
Hey @ryanovas , I first replied 3 weeks ago - I'm keen to help :-) Can you get back to me if this is still an issue you're having? In particular, those 3 questions I asked in my first reply.

**Comment by ryanovas** [comment]
Hi sorry, life and work has gotten busy and I haven't had much time to look at my homelab stuff. I'll try to take another look at this soon

**Comment by jamesread** [comment]
Hey @ryanovas , totally appreciate the life is busy - I've had a lot of that myself recently! No pressure to respond if life is still busy - just reply when you can.

**Comment by jamesread** [comment]
Hey @ryanovas , it's been 2 months - just curious if you're still seeing this startup issue on Ubuntu still?
