### ISSUE TITLE
Apple touch icon support

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#24]
**Is your feature request related to a problem? Please describe.**

Apple devices rely on a separate metadata description for "touch icons". 

https://lynk.icu/F79pi

Originally requested by ScrumpyJack on discord.

**Comment by jamesread** [comment]
Hey @ScrumpyJack , @ksurl , could you test out this snapshot build and tel met know if it looks good for you? https://github.com/OliveTin/OliveTin/actions/runs/1489888896

**Comment by ScrumpyJack** [comment]
I don't recognise the Actions sections on github. Is that a build? Will it run on ARM?

**Comment by jamesread** [comment]
@ScrumpyJack yep, if you click that link, it's just a job that builds a pre-release version of OliveTin. On that page, click on "dist", that will be a download containing all the versions, including ARM.

**Comment by ScrumpyJack** [comment]
yup, that works. awesome.

**Comment by jamesread** [comment]
Great, thanks for letting me know!

**Comment by jamesread** [comment]
This fix made it into the [2022-01-06](https://github.com/OliveTin/OliveTin/releases/tag/2022-01-06) release, therefore, closing this issue.
