### ISSUE TITLE
Document HTTP API for use with 3rd party apps

### ISSUE THREAD

**Issue by mill1000** [OliveTin/OliveTin#25]
Cool app. Excited to see where it goes.

My request is to document the API so other users can easily integrate with 3rd party apps, For example, I'm using it in combination with [HTTP Request Shortcuts](https://play.google.com/store/apps/details?id=ch.rmy.android.http_shortcuts) so I can place OliveTin actions right on my homescreen.

Current API seems simple enough. Actions can be triggered by POSTing to `http://<HOST>/api/StartAction` with the following request
```json
{"actionName":"Start transmission-daemon","arguments":[]}
```

**Comment by jamesread** [comment]
Hey @mill1000 , thanks for your interest in OliveTin, it means a lot :-) 

Sure thing, great idea. I've just grown together some quick docs for you on the standard documentation site. I also generated a OpenAPI JSON spec (v2), and added a Swagger UI. It's not updated automatically as the API changes, but there aren't many changes planned right now (err, any changes), so you should be fairly safe with it!

- https://docs.olivetin.app/_olivetin_api_overview.html for general docs about the API.
- https://docs.olivetin.app/api/ for Swagger

I hope this helps?

**Comment by mill1000** [comment]
Cool. I'll go ahead, that's enough to get me going. I'll close this then.

**Comment by ScrumpyJack** [comment]
> My request is to document the API so other users can easily integrate with 3rd party apps, For example, I'm using it in combination with [HTTP Request Shortcuts](https://play.google.com/store/apps/details?id=ch.rmy.android.http_shortcuts) so I can place OliveTin actions right on my homescreen.

Ooooo, is there a IOS equivalent of this sort of app?

**Comment by mill1000** [comment]
Sounds like newer iOS version have a "Shortcuts" function which can make HTTP requests.

**Comment by jamesread** [comment]
Hey @ScrumpyJack @mill1000 , I just created an issue to track interest in a potential dedicated app; https://github.com/OliveTin/OliveTin/issues/31
