### ISSUE TITLE
ARM binaries not working on older Pi Zero W

### ISSUE THREAD

**Issue by arminus** [OliveTin/OliveTin#26]
Trying to run the current OliveTin_2021-11-19_linux_armv7.deb on an older Pi Zero W with Debian Stretch doesn't work and just returns an "Illegal instruction" message. The last releases which worked where the older armv6 packages.

So I went ahead and built from source which does produce a working binary. What I do miss is a make target or something to turn this into a .deb package, though?

Also, manually copying the new OliveTin binary over an old installation lets me start the server, but then returns a "TypeError: json.actions is undefined" on the web UI. This runs with an existing config.yaml, but I don't see any breaking changes there which would explain that message.

**Comment by jamesread** [comment]
Hey @arminus , woah, something has gone badly wring here. I'm really sorry abiut that, ane thanks for raising the issue. 

The arm release should actually be v5 compatible, the packages are just labeled v7 to match the docker images (docker seems to use v7 as a minimum). 

There also should absolutely not be any breaking config changes - I'm quite strict about keeping compatibility. However, if you're getting an error message sbout json.actions in your browser, thats simply because the webui has had a lot of updates. Be sure to update the files in the webui directory too - I think it's at /usr/share/OlibeTin/ for the deb packages.

I actually have a Pi Zero W powered up on my desk. I don't have  much coding time today, but I'll do my best to test it ASAP.

**Comment by arminus** [comment]
Thanks for the quick response. In my case, the webui from the old OliveTin_2021-05-28_linux_armv6.deb packages was actually at /var/www/olivetin. Copied the new files from the git rep into that folder, works now. Only minor glitch: It says "New Version Available: new-version-3" in the footer, although I am on the newest version.

As for the broken arm build, let me know if I can help you testing.

**Comment by jamesread** [comment]
Hey @arminus . 

Great that you got the webui working, the "new-version-3" is just a relic from some testing I was doijg with the update service - its because you're running a dev build apparently.

**Comment by jamesread** [comment]
Hey @arminus , I finally had time to track this down. It was my mistake, I swapped out the ARM builds from v5 to v7 during testing, and forgot to restore them to v5.

However, I thought it would be good to continue to build two separate versions, for v5 arm[32] and v7 arm[32]. So, with this snapshot build, and for the future, I'll build both; https://github.com/OliveTin/OliveTin/actions/runs/1497082095 

You can download the "dist" folder and test the versions included in there before it makes it into the next release. I hope that works for you - let me know how you get on.

**Comment by arminus** [comment]
Thanks, but I'm afraid that doesn't help since I need armv6 - and that was apparently last built back in May.

If I try to install the v5 from the dist ZIP, I get this:

```
dpkg: error processing archive /home/pi/OliveTin_908edc352fc5555d7edab0ef38e0e24e8cc79b32_linux_armv5.deb (--install):
 package architecture (arm5) does not match system (armhf)
```

The armv7 installs, but again doesn't start but says "Illegal instruction"

Just to be sure: My Pi is a Raspberry Pi Zero W Rev 1.1

**Comment by ashleycawley** [comment]
Hey @arminus if you take a peak in the OliveTin Discord you'll see some shots of me running OliveTin on a 2014 Raspberry Pi A+ ARMv6 the other day.

I will admit on this particular Pi which is just used for testing/experimenting the setup was probably a bit of a mess as numerous weeks before I had attempted to install OliveTin a few ways and failed. But iirc the other night I downloaded that dist.zip James mentioned above and then I ended up un-zipping it, then extracting this archive:
`tar -xvf OliveTin-908edc352fc5555d7edab0ef38e0e24e8cc79b32-linux-arm32v5.tar.gz`

Then I copied and over-wrote the `OliveTin` binary to `/usr/local/bin/`

Moved the config in place with: `sudo mv config.yaml /etc/OliveTin/`
And: `sudo mv OliveTin.service /etc/systemd/system/OliveTin.service`
Restart service: `sudo systemctl restart OliveTin`
Check Service state: `sudo systemctl status OliveTin`

With a bit of luck that might get you up and running. I know it might not be the cleanest but it sounds like your Pi might be in the same (partially installed) state as mine was a while back and that got me up and running so I thought I'd share.

**Comment by arminus** [comment]
@ashleycawley - thanks, I already built my own binary last week, this test is/was actually more about getting the releases "right"...?

**Comment by jamesread** [comment]
@arminus, ahh, I can see what is going on here. It's a problem with the package, rather than just the binary (which should work) as @ashleycawley pointed out. But yeah, now I have a better idea of the problem.

Give me some time to look into this for you - I need to fiddle with the deb packaging to get it to match.

**Comment by jamesread** [comment]
@arminus , ah, brushing up ARM a bit more, it seems v5 = `armel`, and v6 = `armhf`? https://github.com/goreleaser/goreleaser/issues/1026 . Let me try a quick win of spitting out a v6 package for you and see if it works :-)

**Comment by jamesread** [comment]
@arminus , mind testing the .deb of the new v6 build here? https://github.com/OliveTin/OliveTin/suites/4477424457/artifacts/119199484

**Comment by arminus** [comment]
@jamesread I'm sorry:

```
dpkg: error processing archive /home/pi/OliveTin_4c7b4ee7dee63122b22a3642b3e73e0b0b6d44bb_linux_armv6.deb (--install):
 package architecture (armel) does not match system (armhf)
```

How many arms are there ?? ;-))

**Comment by jamesread** [comment]
Thank goodness for that!
