### ISSUE TITLE
OliveTin.service: Failed to execute command: Permission denied

### ISSUE THREAD

**Issue by send2ali** [OliveTin/OliveTin#27]
Hi, Im getting the following permission error on a Pi install following your install guide.

I've tried to 
- run as root, 
- chmod 777 and  u+x 

This is from the logs

Nov 22 11:48:20 RaspberryPi4-03 systemd[26463]: OliveTin.service: Failed to execute command: Permission denied
Nov 22 11:48:20 RaspberryPi4-03 systemd[26463]: OliveTin.service: Failed at step EXEC spawning /usr/local/bin/OliveTin: Permission denied
Nov 22 11:48:20 RaspberryPi4-03 systemd[1]: OliveTin.service: Main process exited, code=exited, status=203/EXEC
Nov 22 11:48:20 RaspberryPi4-03 systemd[1]: OliveTin.service: Failed with result 'exit-code'.
Nov 22 11:48:21 RaspberryPi4-03 systemd[1]: OliveTin.service: Service RestartSec=100ms expired, scheduling restart.
Nov 22 11:48:21 RaspberryPi4-03 systemd[1]: OliveTin.service: Scheduled restart job, restart counter is at 5.
Nov 22 11:48:21 RaspberryPi4-03 systemd[1]: Stopped OliveTin.
Nov 22 11:48:21 RaspberryPi4-03 systemd[1]: OliveTin.service: Start request repeated too quickly.
Nov 22 11:48:21 RaspberryPi4-03 systemd[1]: OliveTin.service: Failed with result 'exit-code'.
Nov 22 11:48:21 RaspberryPi4-03 systemd[1]: Failed to start OliveTin.

**Comment by jamesread** [comment]
Hey @send2ali , sorry that you're getting thrse problems. I can see that you're on a Pi4, but wpuld you mind telling me which package you used to install OliveTin? Thanks.

**Comment by send2ali** [comment]
Hi @jamesread. 
I just used the "1.3 Installation from a .tar.gz manually, using systemd"
(https://docs.olivetin.app/install-targz.html)
followed each step.

**Comment by jamesread** [comment]
Hey @send2ali , I'm sorry, I'm not sure why I didn't reply to this issue sooner. 

It looks like you just need to chmod OliveTin. Could you try running `chmod ugo+x /usr/local/bin/OliveTin`? This is necessary during some manual installs.

**Comment by jamesread** [comment]
@send2ali I assume this has timed out for now. If you still have an issue, please reopen.
