### ISSUE TITLE
Execution results are not displayed correctly

### ISSUE THREAD

**Issue by l20f111164** [OliveTin/OliveTin#272]
**Describe the bug**
Using `popupOnStart: execution-dialog-stdout-only` in the config file or `Waiting for result...` will not show the result of the next execution, the result of the next execution step does not appear

**To Reproduce**
This issue is reproduced whether I use the default configuration file or a new environment installation, and there are no configuration file checks to make this configuration function properly.

**Expected behaviour**
I'd like to be able to quickly display the results of an execution as normal.

**Screenshots**
![image](https://github.com/OliveTin/OliveTin/assets/9441728/8ecd751d-6dcd-468d-89ff-65613296c601)

**Additional context** 
I'm using dpkg to install the deb installer on debian OS.

**Comment by jamesread** [comment]
Hey @l20f111164 , thanks for reporting this issue. Sorry that you're having this problem.

Can you open your browser's development tools (normally just press F12), start the section, and then show a screenshot of the "Console" tab? I want to see if there are any hidden errors. 

Also, do you see the log of you go to the logs page in the sidebar?

**Comment by l20f111164** [comment]
> Hey @l20f111164 , thanks for reporting this issue. Sorry that you're having this problem.
> 
> Can you open your browser's development tools (normally just press F12), start the section, and then show a screenshot of the "Console" tab? I want to see if there are any hidden errors.
> 
> Also, do you see the log of you go to the logs page in the sidebar?

![image](https://github.com/OliveTin/OliveTin/assets/9441728/bf7296c2-03de-47b5-b687-ffedff37c457)

Okay, let's see if this is okay.

**Comment by jamesread** [comment]
@l20f111164 hmm, I cannot seem to reproduce this. The error that you are seeing in the web console is because your browser is refusing to open the execution dialog, because it's already open. However, browsers should just silently ignore this if the execution dialog is already open.

I can see that you're using Chrome, but what version are you running, please? Could you use the "copy" button in your "chrome://version" page, if possible?

**Comment by l20f111164** [comment]
It doesn't feel like it should be a browser issue. I still get this problem with my mobile browser or any other browser.
![image](https://github.com/OliveTin/OliveTin/assets/9441728/5892e3a8-80cb-45d0-8f4e-0f1257755367)
![de02e4bc183791d32ea234e6fb65095](https://github.com/OliveTin/OliveTin/assets/9441728/7f893df7-5c7f-4a1f-88a1-9e1937c9f77e)

It doesn't feel like it should be a browser issue. I still get this problem with my mobile browser or any other browser.

Maybe you can try using the environment I built using docker to see if you can reproduce it.

https://ot.hwen.xyz/

**Comment by jamesread** [comment]
Hmm, I just tried your public instance on my mobile browser and it seems like you're using the default config, and everything is working OK. 

Will try to reproduce more a little later today.

**Comment by l20f111164** [comment]
@jamesread  I tried to get some cases by searching the problem reporting on google to see if it helps you to solve that analyze that problem.

https://github.com/facebook/react/issues/24399
https://github.com/desktop/desktop/issues/7785
https://stackoverflow.com/questions/74797095/why-am-i-unable-to-open-my-dialog-modally-in-javascript

**Comment by l20f111164** [comment]
@jamesread Tried the latest release, still doesn't work, same error message。

**Comment by jamesread** [comment]
Ah the fix hasn't yet made it into a release - but I'll push a release now for you :-) Let me know if it then works :-)

**Comment by jamesread** [comment]
@l20f111164 try 2024.04.28 for me if that's ok, that release includes the proposed fix.

**Comment by l20f111164** [comment]
Indeed, version 2024.04.28 has fixed the issue, thanks!

**Comment by jamesread** [comment]
Great news :-)
