### ISSUE TITLE
Missing jq dependency

### ISSUE THREAD

**Issue by dbradmit** [OliveTin/OliveTin#276]
**Describe the bug**
The jq package is missing.

The [Systemd Control Panel](https://docs.olivetin.app/systemd-control-panel.html#systemd-control-panel) example references "jq (JSON Query)" as a way to process the JSON response from the `systemctl list-units` command. Attempts to utilize jq in shell commands fails with an error of `jq: command not found`.

I _think_ this might only be an issue for Docker installations as the user could manually install jq in other environments. I am somewhat new to all of this and did try manually installing jq but was only successful if I built the image myself. It's either not possible or I am unaware of a way to install a package like jq when using the pre-made images.

When building from scratch I just added 'jq' to the packages to install in the Dockerfile.

```
	microdnf install -y --nodocs --noplugins --setopt=keepcache=0 --setopt=install_weak_deps=0 \
		iputils \
		openssh-clients \
		shadow-utils \
		apprise \
		docker \
		jq \
```

**To Reproduce**
1. Run the latest Docker image from jamesread/olivetin.
2. Access the command line in the running container (for example: `docker exec -it olivetin bin/bash`).
3. Try a command involving jq such as `curl 'https://api.github.com/repos/olivetin/olivetin/commits?per_page=5' | jq '.[0].author.login'`.
4. Response will be `jq: command not found`.

**Expected behavior**
OliveTin should have access to the jq package.

In the example above of `curl 'https://api.github.com/repos/olivetin/olivetin/commits?per_page=5' | jq '.[0].author.login'` the response should be the login name of the author of the latest commit, which at this time is naturally `jamesread`.

**Additional context**
For context, my actual use case for this was that I wanted to display weather info from an API.

This is an example of an OpenWeather API response:

`{"coord":{"lon":10.99,"lat":44.34},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],"base":"stations","main":{"temp":275.62,"feels_like":273.81,"temp_min":273.85,"temp_max":278.3,"pressure":1018,"humidity":98,"sea_level":1018,"grnd_level":948},"visibility":7533,"wind":{"speed":1.8,"deg":285,"gust":1.95},"clouds":{"all":57},"dt":1713494807,"sys":{"type":2,"id":2044440,"country":"IT","sunrise":1713500697,"sunset":1713549890},"timezone":7200,"id":3163858,"name":"Zocca","cod":200}`

I'm using jq to parse and store the response so it can be displayed. The below converts the Kelvin response to Fahrenheit with a single decimal place and stores it as a string.

```
curl -s 'https://api.openweathermap.org/data/2.5/weather?lat=10.99&lon=-44.34' | jq -c '{
  temp: (.main.temp - 273.15),
  temp_min: (.main.temp_min - 273.15),
  temp_max: (.main.temp_max - 273.15)   
} | .temp |= tonumber * (9/5) + 32 | .temp |= (.*10 | floor)/10 | .temp |= tostring | .temp_min |= tonumber * (9/5) + 32 | .temp_min |= (.*10 | floor)/10 | .temp_min |= tostring | .temp_max |= tonumber * (9/5) + 32 | .temp_max |= (.*10 | floor)/10 | .temp_max |= tostring |  {
  temp: "\(.temp)",
  temp_min: "\(.temp_min)",
  temp_max: "\(.temp_max)"
}' > /entities/weather.json
```

This results in a weather.json such as:

`{"temp":"83.3","temp_min":"78.9","temp_max":"86.3"}`

**Comment by jamesread** [comment]
Heya @dbradmit , thanks for taking the time to report this. It certainly would be useful to have jq installed in thd container already, I've just submitted a pull request for this.
