### ISSUE TITLE
Unknown message type from server: LogEntry

### ISSUE THREAD

**Issue by zezulka** [OliveTin/OliveTin#283]
Hello! This is my first time using OliveTin. The installation itself was quite easy but right after the installation, I've I ran into a dead end and would need a bit of help.

**What seems to be the problem?**

When I click on any button in the OliveTin UI, I get an error message box saying `Unknown message type from server: LogEntry`. I've tried Brave and Firefox on a Linux machine.

![Screenshot_2024-04-20_16-47-17](https://github.com/OliveTin/OliveTin/assets/16479949/9b514338-f4a7-4a27-b7ac-873f2e29a85e)

**Can you provide a sosreport?**

```
# Build: 
commit: 09e1de0
version: 2024.04.20
date: "2024-04-19T23:27:13Z"

# Runtime:
os: linux
osreleaseprettyname: PRETTY_NAME="Fedora Linux 38 (Container Image)"
arch: arm64
incontainer: true
lastbrowseruseragent: ""

# Config:
countofactions: 2
countofdashboards: 0
loglevel: INFO
listenaddresssinglehttpfrontend: 0.0.0.0:1337
listenaddresswebui: localhost:1340
listenaddressrestactions: localhost:1338
listenaddressgrpcactions: localhost:1339
timezone: Local
```

**What package/file/container did you use to install OliveTin?**

I've installed OliveTin using a modified version of the [official helm chart](https://github.com/OliveTin/OliveTin-HelmChart). I needed to modify the ingress resource template so that it accepts an ingress class name. Please let me know if you suspect any of my modifications might be related to this issue, I can copy paste here all OliveTin kubernetes resources created by the helm installation.

The version of the docker image being used is 2024.04.20.

**Your config.yaml**

```
InsecureAllowDumpSos: true
```

**OliveTin logs**

```
level="info" msg="OliveTin initializing" commit="09e1de0" date="2024-04-19T23:27:13Z" version="2024.04.20"
level="debug" msg="Value of -configdir flag" value="."
level="info" msg="Setting log level to info"
level="info" msg="OliveTin initialization complete"
level="info" msg="OliveTin started" configDir="/config"
level="info" msg="Starting REST API" address="localhost:1339"
level="info" msg="Starting WebUI server" address="localhost:1340"
level="warning" msg="Could not create themes directory: mkdir /config/custom-webui: read-only file system"
level="warning" msg="Could not read + create installation ID file: open /config/installation-id.txt: read-only file system"
level="info" msg="Found the webui directory" dir="/var/www/olivetin/"
level="info" msg="Starting single HTTP frontend" address="0.0.0.0:1337"
level="info" msg="Update check complete" NewVersion="none"
level="info" msg="Action requested" actionTitle="Ping Google.com" tags="[]"
level="info" msg="Action parse args - Before" actionTitle="Ping Google.com" cmd="ping google.com -c 1"
level="info" msg="Action parse args - After" actionTitle="Ping Google.com" cmd="ping google.com -c 1"
level="info" msg="Action starting" actionTitle="Ping Google.com" timeout="3"
level="info" msg="Action finished" actionTitle="Ping Google.com" exit="0" stderr="" stdout="PING google.com (142.251.36.110) 56(84) bytes of data.\n64 bytes from prg03s11-in-f14.1e100.net (142.251.36.110): icmp_seq=1 ttl=117 time=8.56 ms\n\n--- google.com ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 8.559/8.559/8.559/0.000 ms\n" timedOut="false"
```

**Screenshot of WebDeveloper console logs**

This is the WS message the frontend receives once I click on the "Ping Google.com" button:

![Screenshot_2024-04-20_16-02-51](https://github.com/OliveTin/OliveTin/assets/16479949/28ee4c2b-3416-4f44-a186-79a5d3f3f23c)

**Comment by jamesread** [comment]
Okay, I introduced this bug last night. Will push an emergency fix in a minute.

**Comment by jamesread** [comment]
2024.04.021 building now, I just built it on my phone without testing, so I can't be sure that it will work.

**Comment by jamesread** [comment]
@zezulka , sorry for the inconvenience of this issue, but I believe I managed to fix it in 2024.04.021. Would you mind updating and trying it now? 

I was making some fixes last night and made soem changes in an area that doesn't have test coverage - I'll try to work on that.

**Comment by zezulka** [comment]
Yes, it works now as expected! Thanks for the quick fix.

**Comment by jamesread** [comment]
@zezulka great, and sorry for the inconvenience!
