### ISSUE TITLE
Local images

### ISSUE THREAD

**Issue by swoop124** [OliveTin/OliveTin#29]
Hello,

Browsers with no internet, get no HTML-Icons. 
I'd like the possibility to load Icons from local store.

regards

**Comment by jamesread** [comment]
Hey @swoop124 , thanks for raising the issue. 

So, I'm personally a fan of HTML Unicode icons that are rendered natively in the browser (these are actually text characters, not images), and one of the benefits is that they work without an internet connection. You can see documentation on how to set these up here; https://docs.olivetin.app/_icons.html#_unicode_icons_emoji

However, if you would like to use locally stored images, you could do that quite easily. If you are running a Docker Container, you could create a image called "myIcon.png", and then you could bind mount a directory like "/opt/myimages" to "/var/www/olivetin/images" inside the container. OliveTin will serve that images directory on a webserver like normal. Then you can just write raw HTML for the icon in the config file; 

----
actions:
    - title: HTML (jpg/png/etc) icon
      icon: '<img src = "icons/myIcon.png" width = "48px"/>'
      shell: docker ps
----

This is shown in the documentation too; https://docs.olivetin.app/_icons.html#_full_html_icons_img_src (but the icons in that example are on the public internet).

**Comment by jamesread** [comment]
@swoop124 , I've decided that this would be best as part of the documentation, and decided to add a whole extra section and example for this.

https://docs.olivetin.app/_icons.html#_saving_and_serving_icons_for_offline_use

I think that should do everything you're asking for - so I am going to close this issue for now. If you think differently, or want to add extra comments, please do feel free to re-open the issue anytime.
