### ISSUE TITLE
Display output (stdout/stderr) from commands

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#3]
First requested by `SalvatoreParadise` here; https://www.reddit.com/r/selfhosted/comments/nfqi5m/olivetin_a_simple_web_interface_to_run_linux/

**Is your feature request related to a problem? Please describe.**
I'd like to see output (stdout/stderr) from commands. 

**Describe the solution you'd like**
Need to think of a design that makes sense. It would probably be frustrating to see the output from all commands every time. Probably it would be a button you could click after running a command to see the output.

Maybe the config file needs an option to enable/disable command output display too.

The stdout/stderr is already sent to the browser - see the network tab of your favourite browser's Web Developer tools. It's just the Javascript in the webui needs to do something useful with it.

**Comment by RedLeeder** [comment]
I 2nd this request!

**Comment by jamesread** [comment]
I'm starting to make progress on this in the `log-support` branch. Here's a screenshot of what it looks like so far - interested in feedback;

![image](https://user-images.githubusercontent.com/2025715/126000191-bbe16a5a-a868-441c-b7b9-d10c959bfdb8.png)

**Comment by jamesread** [comment]
Today's release - 2021-07-19 - now includes this early feature.

@RedLeeder - thoughts?
