### ISSUE TITLE
Change dashboard url to /myDash instead of /#myDash

### ISSUE THREAD

**Issue by vutsalsinghal** [OliveTin/OliveTin#306]
currently the dashboards are have a `#` subpath (like `olivetin.mydomain.com/#myDashboard`) which cannot be directly accessed. It would be nice to have a dedicated subpath like `olivetin.mydomain.com/myDashboard` which can be directly accessed. 

My use case is to have a dashboard as iFrame in [homepage](https://gethomepage.dev/)

**Comment by jamesread** [comment]
@vutsalsinghal , released in version 2024.05.13 . Let me know if that is working as expected?

**Comment by vutsalsinghal** [comment]
@jamesread could the dashboards be on something like `/d/myDashboard` or `/dash/myDashboard` or `/dashboard/myDashboard` or simply `/myDashboard` ?

I've to set a special rule in nginx for a particular OliveTin dashboard but `#` is not recognised character by nginx and escaping it with `%23` doesn't work as well

**Comment by jamesread** [comment]
@vutsalsinghal I just pushed a new release last night, 2024.08.14 has a totally rebuilt navigation - so dashbpards are now accessible from /myDashboard, and there is /logs, /diagnostics, etc. 

I think this is a much more scalable navigation system. Can you test it?

**Comment by vutsalsinghal** [comment]
I'm able to see the latest changes! Love it ❤️ 

Thank you 🙏🏼
