### ISSUE TITLE
Small UI issues in execution dialog

### ISSUE THREAD

**Issue by steveiliop56** [OliveTin/OliveTin#343]
**Describe the bug**
Hello, while I was playing around with olivetin on my mobile I noticed that a) the Unicode character used for maximizing the execution dialog isn't rendered on Android b) xterm is not using the full width of the dialog.

**To Reproduce**
1. Run an action
2. Go to logs
3. Click the action
4. Xterm is not stretched across the screen
5. The maximize button is not rendered correctly

**Expected behavior**
Xterm should stretch across the screen, the Unicode character should be change to something all devices use.

**Comment by steveiliop56** [comment]
Oh I forgot to upload the screenshot, here it is:
![Screenshot_20240703_194858_Chrome](https://github.com/OliveTin/OliveTin/assets/106091011/c8696c12-d1a4-4ad0-a4e1-4a48b8b52aa0)

**Comment by jamesread** [comment]
Yeah, this is a Chrome bug. I've just pushed a fix for it in Pull Request #345 - so it will be included in the next release of OliveTin in an hour or so. Thanks for reporting it!

**Comment by steveiliop56** [comment]
I would also recommend adding some margin to the terminal, I think it would look better. Don't forget the Unicode issue :)

**Comment by jamesread** [comment]
@steveiliop56 , do you mind upgrading to 2024.07.07, refresh, and see if this fixes it?

**Comment by steveiliop56** [comment]
Hello,

The terminal issue is fixed (from the previous version) what do you want me to test in the new version?

**Comment by jamesread** [comment]
@steveiliop56 could you test 2024.07.13 , that should fix the last issue with the maximize icon.

**Comment by steveiliop56** [comment]
Yeah it's working just fine now thanks!
