### ISSUE TITLE
Iconify not working when adding color

### ISSUE THREAD

**Issue by YouveGotMeowxy** [OliveTin/OliveTin#351]
**Describe the bug**

When I go to the Iconify website, select an icon, and add a custom color to it, OliveTin doesn't recognize it when I add it to the `icon:` property.

**a couple example icons:**

    <iconify-icon icon="solar:restart-line-duotone"  style="color: #2B99EE"></iconify-icon>

    <iconify-icon icon="cbi:plex"  style="color: #CF900C"></iconify-icon>

**Side note:**

the icon code given by the site itself has a double-space before `style=`. I've tried using only a single space there, as well as keepin as is, but nothing either way.

**Comment by YouveGotMeowxy** [comment]
Ok, put a lil more thought into it and noticed the colon in the strings were confusing the yaml, so wrapping the entire line in single-quotes solved it, and they now show in OT.

    '<iconify-icon icon="cbi:plex"  style="color: #CF900C"></iconify-icon>'

**Comment by jamesread** [comment]
I actually didn't know this was possible, but, awesome 😎 Glad you found the fix.
