### ISSUE TITLE
Arguments can be null

### ISSUE THREAD

**Issue by crnakad** [OliveTin/OliveTin#36]
I would like to add arguments to my command and have the possibility to leave the value empty
example:

  shell: ansible-playbook --extra-vars "nginx_host={{ nginxhost }} default_location={{ defaultlocation }} machine={{ machine }} port={{ port }} location={{ location }}" -i /tmp/inventory.yml /tmp/playbook.yml

and leave {{ defaultlocation }} argument empty if I don't want to provide a value there

**Comment by jamesread** [comment]
Hey @crnakad , thanks for taking the time to report this feature request - sorry that it's taken quite a while to reply to you. 

I'll certainly take a look at this for an upcoming release.

**Comment by jamesread** [comment]
Hey @crnakad thanks gor uour patience, this was just fixed in #292 :-)
