### ISSUE TITLE
How to setup dev env in windows

### ISSUE THREAD

**Issue by wushuzh** [OliveTin/OliveTin#362]
Hello,  

Thanks for this wonderful project.

I'd like to know if it's possbile to setup a dev env in windows ? If yes, would you please give a few guide so I can investigate more ?

I don't mean to deploy OliveTin in windows but only to use windows env to study and debug code. 

Here is what I did and the following error I got during executing 'make'

```
C:\Users\me\OliveTin>choco install git go protoc make -y
...
C:\Users\me\OliveTin>git clone https://github.com/OliveTin/OliveTin.git
C:\Users\me\OliveTin>cd OliveTin
C:\Users\me\OliveTin>make grpc
...
buf generate
C:\Users\me\OliveTin>make
GOOS=linux go build -o OliveTin github.com/OliveTin/OliveTin/cmd/OliveTin
'GOOS' is not recognized as an internal or external command,
operable program or batch file.
make: *** [Makefile:7: daemon-compile-x64-lin] Error 1
```

**Comment by jamesread** [comment]
Hey, and thank YOU for your interest in developing OliveTin! :-) 

I develop OliveTin on Linux, and cross compile for other architectures (goreleaser handles most of that nowadays). However, let's try and get this working on Windows. 

The error you're seeing is line 7 in the Makefile, it's trying to set the environment variable GOOS (Go Ooerating System), and run the compiler in the same command. Very normal for Linux, but Windows doesn't support this syntax. 

I'm not in front of my Windows machine to test right now, just typing this on my phone, by try: 

Change the default target from "lin" to "win" on line 1. 

On line 10, just remove "GOOS=windows GOARCH=amd64" - go on Windows should default to those values anyway. 

Buf/grpc will probably be the hardest part, but go will install all those little plugins and dependencies for you at least. 

Let me know how you get on @wushuzh !

**Comment by wushuzh** [comment]
Yes, you suggestions works.  I make the changes and the exe file is generated successfully.

Here are 2 follow-ups, I'd like to know your opinion.

1. I checked [the doc of `go env`](https://pkg.go.dev/cmd/go@go1.22.5#hdr-Print_Go_environment_information). I can set the env to desire value before compile, then I can unset it right after compiling ? It seems to me unset will restore to its default value.

```
diff --git a/Makefile b/Makefile
index 8491e5fc..e2b08fec 100644
--- a/Makefile
+++ b/Makefile
@@ -1,13 +1,19 @@
 compile: daemon-compile-x64-lin
 
 daemon-compile-armhf:
-       GOARCH=arm GOARM=6 go build -o OliveTin.armhf github.com/OliveTin/OliveTin/cmd/OliveTin
+       go env -w GOOS=arm GOARM=6
+       go build -o OliveTin.armhf github.com/OliveTin/OliveTin/cmd/OliveTin
+       go env -u GOOS GOARM
 
 daemon-compile-x64-lin:
-       GOOS=linux go build -o OliveTin github.com/OliveTin/OliveTin/cmd/OliveTin
+       go env -w GOOS=linux
+       go build -o OliveTin github.com/OliveTin/OliveTin/cmd/OliveTin
+       go env -u GOOS
 
 daemon-compile-x64-win:
-       GOOS=windows GOARCH=amd64 go build -o OliveTin.exe github.com/OliveTin/OliveTin/cmd/OliveTin
+       go env -w GOOS=windows GOARCH=amd64
+       go build -o OliveTin.exe github.com/OliveTin/OliveTin/cmd/OliveTin
+       go env -u GOOS GOARCH

 daemon-compile: daemon-compile-armhf daemon-compile-x64-lin daemon-compile-x64-win
```

2. I also check those two stackoverflow questions about detecting OS in Makefile, but I am not sure I can make it right.

- [Makefile that distinguishes between Windows and Unix-like systems](https://stackoverflow.com/questions/4058840/makefile-that-distinguishes-between-windows-and-unix-like-systems)
- [OS detecting makefile](https://stackoverflow.com/questions/714100/os-detecting-makefile)

**Comment by wushuzh** [comment]
I'd like to know if other targets of makefile can be executed in windows as well.

I've installed podman in my windows and launch the `podman mahine init` and wait. But due to my network connection, it may take a long time to finish. I will sync the progress later.

If any suggestions on next actions, let me know.

**Comment by jamesread** [comment]
Hey @wushuzh , what is your ultimate end goal? Is it important that you build arm/linux targets from Windows? 

I'm just asking, because if you are just interested in developing features for OliveTin, then just compiling and testing on Windows is likely to be fine, and when you submit a pull request, the build system will build all targets anyway. 

Adjusting the makefile with `go env` is a sensible cross-platform fix, I'd be happy to accept that patch if you want to submit it as a PR. 

We could also add another target called something like `daemon-compile-currentenv`, which does not get any `go env`, and just uses the current environment / platform.

**Comment by wushuzh** [comment]
To be honest, I'm still at a beginner's level, so I'd like to get a handle on compiling and testing the components in this project. This might help me understand the entire compilation process and ensure that any future code changes I make are thoroughly tested in my local environment before submitting pull requests.

Here's my original plan for getting familiar with the project:

- Run the integration test suite locally: This will give me a comprehensive overview of how the project's components work together.

- See if I can add a test case: Once I've grasped the existing test cases, I'll look for areas where I think testing could be strengthened and write a new test case accordingly.

- Understand open issues: I'll review the project's open issues and choose one that aligns with my skills and interests. I'll try to reproduce it in my local environment. If successful, I want to join the discussion and contribute my thoughts on potential solutions, even try to contribute a fix.

I'd like to know your suggestions :)

**Comment by jamesread** [comment]
#364 gladly accepted and merged. Great job on the PR, as I commented in the PR comments :-) 

Ok to close this issue, or need anything else at this stage?

**Comment by wushuzh** [comment]
Yes, the issue can be closed. The basic dev tasks are working on windows.

Thanks so much for merging my first Go project PR! It's a small win for me, but a huge step forward in my Go learning journey. 

I'm gonna dive deeper into the project now. Hopefully I might contribute more PRs to OliveTin later on :)
