### ISSUE TITLE
The type of metrics olivetin_actions_requested_count shall be counter not gauge

### ISSUE THREAD

**Issue by wushuzh** [OliveTin/OliveTin#365]
**Describe the bug**

When I read the doc [Prometheus](https://docs.olivetin.app/prometheus.html#prometheus), I came across the metrics `olivetin_actions_requested_count`, is it better to set its type as counter not gauge ?

**Additional context**

I am thinking about adding more metrics for OliveTin, I will come back to this topic later.

**Comment by jamesread** [comment]
Yep, `olivetin_actions_requested_count` should be a counter, as the number of requested actions will only ever increase.

However `olivetin_config_actions_count` should stay as a gauge, as it could go down when people remove an action from the config during runtime.

**Comment by wushuzh** [comment]
Hi James,

Just wanted to let you know I submitted a PR to address this issue. I'd really appreciate it if you could take a look and give it a review.

If you see anything that needs tweaking, please don't hesitate to let me know :)

**Comment by wushuzh** [comment]
I see the PR has been merged. Thanks James.

**Comment by jamesread** [comment]
@wushuzh thank YOU for the 😊
