### ISSUE TITLE
Add more prometheus metrics to OliveTin application

### ISSUE THREAD

**Issue by wushuzh** [OliveTin/OliveTin#366]
I hope to beef up OliveTin's monitoring with some new prometheus metrics!

Here's what I'm thinking:

1. **Track action executions**: We can use counter metrics to see how many actions are running overall, including successes, failures, timeouts, and terminations. Or should we dive deeper and track each action type (trigger, cron, startup, file changes, calendar) separately? We can leverage the existing tags property for this. 

2. **Gauge long-running actions** : For actions with custom timeouts, gauges might be a better fit. These metrics would track average and maximum execution duration to pinpoint potentially slow actions. Also Actions with settings like maxConcurrent or maxRate might also need dedicated metrics.  All these data could be helpful for [#298](https://github.com/OliveTin/OliveTin/issues/298) as well.

3. **Log file metrics (watch the disk space!)**: If log files are configured, we can create counter metrics to track the number of entries or total file size. Just keep an eye on disk usage to avoid filling it up.

By adding these metrics, we'll get a much clearer picture of how OliveTin's actions are performing and how they're using resources.

**Comment by jamesread** [comment]
@wushuzh I think that is a fantastic idea, fully supportive :-) As a very aggressive user of Prometheus myself, I can never have enough Prometheus Metrics to be honest!

**Comment by jamesread** [comment]
Hey @wushuzh , are you still interested in doing this? I'd be hsppy to help with anything you need?
