### ISSUE TITLE
set usedConfigDir using os compatible module filepath

### ISSUE THREAD

**Issue by wushuzh** [OliveTin/OliveTin#368]
Hey James

I ran into an issues with the integration tests when running the app in local process mode on Windows.

After some debugging, I believe the problem stems from function `config.Reload`. When it tries to grab the path from the viper used config file, module `path` can't handle Windows-style paths correctly. Without finding and loading the expected entities, it throws off the test and prevents it from completing following checks.

I'm planning to submit a pull request (PR) soon to address this. Please help to confirm if you think I've identified the root cause? Also, let me know if the PR might need any additional tweaks.

Thanks

**Comment by wushuzh** [comment]
#369 Here is the PR, please help to review

**Comment by wushuzh** [comment]
Also ran `daemon-codestyle` on the code, and it flagged some minor formatting issues.

Wondering if you're seeing the same thing on your Linux development environment?

```
diff --git a/cmd/OliveTin/main.go b/cmd/OliveTin/main.go
index b1ccf4a9..1c6b091d 100644
--- a/cmd/OliveTin/main.go
+++ b/cmd/OliveTin/main.go
@@ -20,8 +20,8 @@ import (
        config "github.com/OliveTin/OliveTin/internal/config"
        "github.com/spf13/viper"
-       "strconv"
        "os"
+       "strconv"
 )

 var (
```

```
go version go1.22.5 windows/amd64
```

**Comment by wushuzh** [comment]
Hey @jamesread do you reproduce the same format change after executing `go fmt` with the `cmd/OliveTin/main.go` ?

**Comment by jamesread** [comment]
Hey @wushuzh , just a quick note to say I'm not ignoring you, but I've got a lots of requests on my free time at the moment, taking away from OliveTin dev time. 

I think you're doing fantastic work, and I really thank you for your contributions, but I'll need at least a couple more days before I can get back to you, sorry! :-/

**Comment by wushuzh** [comment]
Hi @jamesread 

You've done a fantastic job managing this project. You've kept track of everything clearly. We can easily handle the rest when we have time. Your groundwork is solid, so there's no need to rush. Often, the best ideas come after we've thought things through and gotten input from everyone. This takes time.

I'm going on vacation next week and won't be available to discuss the issues. Also I'm hoping to squeeze in some time to learn about the technology we're using. I've been reading up on gRPC. I'm confident I can contribute more in the future. :-)

**Comment by jamesread** [comment]
Hey @wushuzh , thanks for your kind words :-) 

I merged your PR, and `make daemon-codestyle` seemed to run clean (it also runs on PRs), so no problems there. Closing this as I think everything is fine!
