### ISSUE TITLE
Keep button disabled until the shell command is done

### ISSUE THREAD

**Issue by rguzmaa** [OliveTin/OliveTin#40]
Would it be possible to keep the button disabled until the shell command is done, even when you leave/refresh the page?

Current behavior:
You hit the button, says "Waiting" and stays grayed out. If I leave or refresh the page, the button is available to be pressed again. The shell is still running in the background and works perfectly though.

Desired behavior:
You hit the button, turns to "Waiting or Running". If you leave the page or refresh it stays like that until the script finishes.

**Comment by jamesread** [comment]
Hey @rguzmaa , thanks for taking the time to write this up as a Github issue. 

This absolutely makes sense. Currently, the way the web interface works means the buttons are refreshed every 3 seconds (approximately), but the code in the background does not "disable" the buttons while a command is running.

I think that this is a sensible thing to add, I'll consider it for the next release :-)

**Comment by jamesread** [comment]
I added this to OliveTin at some point in 2023 and didn't notice this issue to resolve it :-) Done!
