### ISSUE TITLE
{{output}} in shellAfterCompleted skips execution

### ISSUE THREAD

**Issue by sdahlbac** [OliveTin/OliveTin#419]
**Describe the bug**
https://discord.com/channels/846737624960860180/1291375667316916355

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

I thought that I would be able to workaround this by doing something including a link to actual log by using `{{ot_executionTrackingId}}` (and possibly also `{{ot_username}}` but those do not seem to be available in `shellAfterCompleted`

**Comment by jamesread** [comment]
Thus was a weird bug, but I managed to find what it was. OliveTin was silently failing because the "output" variable was undefined. I fixed this by printing warning messages whenever issues occur with shellAfterCompleted, and changed the way variables are validated in this step.
