### ISSUE TITLE
Log the user who executed the action

### ISSUE THREAD

**Issue by hialvaro** [OliveTin/OliveTin#422]
I think it would be great if OliveTin logged what user executed a task. The current logs are great, but I think a missing key piece is knowing who executed that action right in the logs. Something like this:

![image](https://github.com/user-attachments/assets/2506d8e3-b9fb-42fb-8feb-df5135fd76a4)

**Comment by jamesread** [comment]
Hey @hialvaro , I really liked this suggestion, so I've implemented it. Thank you very much - I like the mock up screenshot you created as well! 

I went for a slightly different visual design, I  hope this works for you; 

![image](https://github.com/user-attachments/assets/e4a481a7-5276-4c70-bd06-309871274408)

**Comment by hialvaro** [comment]
That's awesome. Thanks.

**Comment by jamesread** [comment]
This should now be in the latest builds. Can you test and provide some feedback if this matches what you needed?

**Comment by hialvaro** [comment]
Been testing, seems to be just what I was looking for :)

Thanks!
