### ISSUE TITLE
OliveTin can't access Channels or Ping Channels running on my iMac host

### ISSUE THREAD

**Issue by ARRampton** [OliveTin/OliveTin#423]
**What seems to be the problem?!**

OliveTin appears to be running with its Web Page showing expected buttons but I think there is no correct network link from Channels back to olivetin
```
Post Install Healthcheck
Checking your OliveTin installation...
(extended_check=false)

----------------------------------------

Checking that your selected Channels DVR server (localhost:8089) is reachable by URL:
HTTP Status: 200 indicates success...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 8089: Connection refused
HTTP Status: 000
Effective URL: http://localhost:8089/

----------------------------------------

Checking that your selected Channels DVR server's data files (/mnt/localhost-8089) are accessible:
Folders with the names Database, Images, Imports, Logs, Movies, Streaming and TV should be visible...

total 16
drwxr-xrwx  11 root root   352 Oct  8 01:04 .
drwxr-xr-x   1 root root  4096 Oct  8 02:24 ..
-rw-r--rw-   1 root root  8196 Oct 10 02:50 .DS_Store
drwxr-xrwx  33 root root  1056 Oct  9 04:58 Database
drwxr-xrwx 448 root root 14336 Oct 10 02:23 Images
drwxr-xrwx   6 root root   192 Mar 23  2022 Imports
drwxr-xrwx   5 root root   160 Jun  6  2021 Logs
drwxr-xrwx  21 root root   672 Sep 28 19:59 Movies
drwxr-xr-x   5 root root   160 Oct  8 01:04 Olive Tin
drwxr-xrwx   5 root root   160 Oct  2 23:21 Streaming
drwxr-xrwx 143 root root  4576 Oct 10 01:13 TV

----------------------------------------

Checking that your selected Channels DVR server's log files (/mnt/localhost-8089_logs) are accessible:
Folders with the names data and latest should be visible...

total 4
drwxr-xr-x 2 root root   64 Oct  8 01:04 .
drwxr-xr-x 1 root root 4096 Oct  8 02:24 ..

----------------------------------------

Here's a list of your current OliveTin-related settings:

HOSTNAME=olivetin
CHANNELS_DVR=localhost:8089
CHANNELS_DVR_ALTERNATES=
CHANNELS_CLIENTS=Lounge TV Bath
ALERT_SMTP_SERVER=smtp.mail.me.com:587
ALERT_EMAIL_FROM=[Redacted]@me.com
ALERT_EMAIL_PASS=[Redacted]
ALERT_EMAIL_TO=[Redacted]@mac.com
UPDATE_YAMLS=true
UPDATE_SCRIPTS=true
PORTAINER_TOKEN=[Redacted]
PORTAINER_HOST=docker-host
```
----------------------------------------

Here's the contents of /etc/resolv.conf from inside the container:

```
# Generated by Docker Engine.
# This file can be edited; Docker Engine will not make further changes once it
# has been modified.

nameserver 127.0.0.11
search iMac-i5-G7-Andy.local
options ndots:0

# Based on host file: '/etc/resolv.conf' (internal resolver)
# ExtServers: [192.168.65.7]
# Overrides: [search]
# Option ndots from: internal

----------------------------------------

Here's the contents of /etc/hosts from inside the container:

127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.3	olivetin
```

**Can you provide a sosreport?**

A sosreport really helps us to help you, by providing critical information about your install. If you can generate a sosreport, please copy and paste the output here.

How to generate a sosreport: https://docs.olivetin.app/sosreport.html

**What package/file/container did you use to install OliveTin?**
Configured from Portainer 2.21.2
eg: OliveTin -
eg: Container from Dockerhub - 
OliveTin version: '3.9' 2024.04.09
DockerDesktop 4.34.2 (167172)

**Your config.yaml**

```
[config yami.txt](https://github.com/user-attachments/files/17321315/config.yami.txt)

```

**OliveTin logs**

If possible, please copy and paste your OliveTin logs from when the error happened.

**Screenshot of WebDeveloper console logs**

If you know how, and if you think it's relevant, a screenshot of the
WebDeveloper console from when you clicked a button is often really helpful.

**Anything else?**

**Comment by jamesread** [comment]
Hey @ARRampton , thanks for raising this. 

Sorry that you're having problems, but I'm afraid I'm not entirely sure what it is you're trying to do. You say "I think there is no correct network link from Channels back to olivetin", however, what is "Channels"? Is this another app that is trying to talk to OliveTin, or is OliveTin trying to talk to this Channels app? 

I'm also not quite sure if you're running on Portainer, or on your iMac, etc. Could you say more?

If you could go into a bit more detail, that would be helpful.

**Comment by ARRampton** [comment]
Hi JamesThanks for replying to my issueChannels in running on my iMac host MacOSI think I have resolved my issue by enabling host networking in Docker Desktop resources (not seen this requirement mentioned)I will now test the channel Comskip preferences but I would appreciate an understanding of how olivetin achieves its tasks in ChannelsBest regardsAndy RamptonWillow HouseNorth RoadBathBA2 6HTHome  01225 923898Mobile 07989 743419








***@***.*** On 10 Oct 2024, at 22:47, James Read ***@***.***> wrote:﻿
Hey @ARRampton , thanks for raising this.
Sorry that you're having problems, but I'm afraid I'm not entirely sure what it is you're trying to do. You say "I think there is no correct network link from Channels back to olivetin", however, what is "Channels"? Is this another app that is trying to talk to OliveTin, or is OliveTin trying to talk to this Channels app?
I'm also not quite sure if you're running on Portainer, or on your iMac, etc. Could you say more?
If you could go into a bit more detail, that would be helpful.

**Comment by jamesread** [comment]
Hey @ARRampton , glad that you've got your networking issue resolved. 

OliveTin is used for just running commands - did someone suggest you using it with this channels app? What is it you want to do?

**Comment by ARRampton** [comment]
HiRecommended as a way of turning comskip off on specific channels (UK BBC) so how can it achieve this?Andy RamptonWillow HouseNorth RoadBathBA2 6HTHome  01225 923898Mobile 07989 743419








***@***.*** On 11 Oct 2024, at 18:34, James Read ***@***.***> wrote:﻿
Hey @ARRampton , glad that you've got your networking issue resolved.
OliveTin is used for just running commands - did someone suggest you using it with this channels app? What is it you want to do?

**Comment by jamesread** [comment]
I'm afraid I've never heard of channels / comskip. Please go back to the original person that suggested this.
