### ISSUE TITLE
Live command output

### ISSUE THREAD

**Issue by aristosv** [OliveTin/OliveTin#43]
**What seems to be the problem?!**
Is there a way to show a more prominent output when a button is pressed?
I realise I can go to Logs > stderr, or Logs > stdout, but it would be nice if I could see an output of the command as soon as I press a button. Perhaps a popup, or a side menu, showing what is going on with the command I just executed.

A good example is rundeck. It shows in real time the output of the command, a kill button and a progress bar. I realise of course this is a young project. These are just suggestions for future features.

<img width="967" alt="Greenshot 2022-02-05 17 47 53" src="https://user-images.githubusercontent.com/528302/152648695-fdcb8d11-6f41-4377-b32e-58cb9de3cd2a.png">

**What package/file/container did you use to install OliveTin?**
OliveTin_2022-01-06_linux_arm64.deb

**Comment by jamesread** [comment]
Hey @aristosv , indeed, this is quite a commonly requested feature - a "popup" once done / to view progress.

At the moment, OliveTin only gets logs once the command exits (or times out and is killed). I'll have to look into doing something like log streaming to make this meaningful. 

I'll accept this feature request, but it might take a little while to get this one implemented.

**Comment by l20f111164** [comment]
We strongly recommend supporting this feature, which would be perfect if implemented.

**Comment by jamesread** [comment]
Hey, I've just had some time to work on this, and wanted to share a development video that calls out some relevant changes. Does this look like it's going in the right direction?

https://youtu.be/vWAD04Wpa8U

**Comment by FieldofClay** [comment]
Those features are a step in the right direction for my use case. It is great to have stdout popup to see the output of the command. Adding streaming stdout would be the final piece, so you could for example, see which task in the playbook is currently running.

I think a progress bar is a step too far, you'd need to time previous runs to guess or somehow pull it from the command (if it outputs an easily captured %). Not worth the effort and goes beyond the simplicity of the project.

**Comment by l20f111164** [comment]
![image](https://github.com/OliveTin/OliveTin/assets/9441728/e577f801-4dbd-4a6c-9de5-9b68bcc933ff)
![image](https://github.com/OliveTin/OliveTin/assets/9441728/9373353e-6142-4c72-b5a8-cae7953be167)

There's still a bit of a problem with this real-time command output, I've downloaded the latest version and the historical version and installed them on different devices and they keep getting stuck and not following.

**Comment by jamesread** [comment]
[e641e9a](https://github.com/OliveTin/OliveTin/commit/e641e9aafde486918aa485ba4b9a7880b1d64e6d) contains early support for killing commands. :-) Work in progress.

**Comment by jamesread** [comment]
I need to break this issue down into it's constituent parts - I've just added kill support which will make the next release very shortly, so I'm going to remove "kill button" from the issue title. I'm also going to drop the progress bar support into a new issue, and name it more like "estimated time". This would need log support and a few other things. 

Therefore this issue will be used to track "Live command output" - which is what a lot of people would like to see.

**Comment by jamesread** [comment]
Hey everyone, release 2024.06.01 now includes support for live command output! 

Add `popup-on-start: execution-dialog` to make use of it, or open the dialog manually from the logs view to see it. 

There are several UI bugs I'm aware of, which I'll try to start fixing up in the next 24 hours, but this is such a big feature that so many people wanted, that I just wanted to get in to people as quickly as possible - there are probably some bigger bugs that I've not yet found!

I hope this is useful for you all!

**Comment by jamesread** [comment]
I've pushed a fix for the UI bugs, so I am closing this now. Any new issues with the live command output can be separate GitHub issues.
