### ISSUE TITLE
Local user login not working after ver. 2024.10.18

### ISSUE THREAD

**Issue by rafaelwo-gh** [OliveTin/OliveTin#460]
Web is not showing logged in local user. Top right corner stays with "Login | guest"
Actions that use ACLs with that user are disabled (this is expected).
The problem exists in Edge and Safari (iphone). It does not exist in Chrome. Edit - it also exists in Chrome.
Probably caused by duplicated olivetin-sid-local cookies (session + the new one). Session one has a Path: /api, the other one has Path: /
Manually removing the session type cookie is temporarily fixing the issue but only for the affected browser tab.

This works as expected in version 2024.10.18 and is not working in later versions.

1. Use Edge browser; do not open OliveTin in other browsers or other tabs, keep only one instance open
2. Open Developer tools and monitor cookies
3. Try login with a local user
4. 2 olivetin-sid-local cookies exist and login does not appear to work

**Comment by jamesread** [comment]
Hey @rafaelwo-gh , sorry about this issue :-( 

OliveTin was setting the cookie with just the current path, and for the lifetime of the session, but correct cookies are now: Path = "/" and Age = 1 year. 

Could you delete the cookies you have set for "/api" and see if that works now?

**Comment by rafaelwo-gh** [comment]
Hi James. I can manually remove it but the cookie is recreated next time.
For example I click on login, remove the /api cookie + f5 (temporary fix), logout and then when try login back the cookie is there again (both of them). Just pressing logout is recreating it.

**Comment by jamesread** [comment]
Ahh, I see what is happening. Okay, let me push a bugfix for you.

**Comment by jamesread** [comment]
@rafaelwo-gh Please could you try the 2024.11.02 version and see if that is working better for you? It includes a bugfix for this behavior.

**Comment by rafaelwo-gh** [comment]
@jamesread Works ok now. Thanks.

**Comment by jamesread** [comment]
Great, I was hoping that would do the trick!
