### ISSUE TITLE
Option to hide footer

### ISSUE THREAD

**Issue by RuggyBearLA** [OliveTin/OliveTin#47]
It would be nice to be able to have an option to hide the footer entirely.  In my instance, I'm loading OliveTin in a frame with limited real estate, so I'm getting a scroll bar that I'd like to tidy up.  This would be similar to hiding the "navigation" buttons.

**Comment by jonesrussell** [comment]
Attempted at #48

**Comment by jamesread** [comment]
Hey @RuggyBearLA , thanks very much for taking time to raise this feature request. I think that other people would find this very useful as well. 

@jonesrussell , thanks so very much for raising a PR for this, it should be merged soon!
