### ISSUE TITLE
get version via API

### ISSUE THREAD

**Issue by meonkeys** [OliveTin/OliveTin#479]
Is there a way to get a version string via the API?

If not, could we add one? I might be able to help.

I'd like to make a [Homer](https://github.com/bastienwirtz/homer) card for OliveTin, and this would be easiest if I could just hit `https://olivetin.example.com/api/version` or something.

I suppose exposing the server version number might be a security concern for some folks, but not me.

I think I can also get it right from the HTML response body if we don't want to add it to the API.

**Comment by jamesread** [comment]
Heya. OliveTin exposes it's current version via a file that is not technically part of the API, but it used for rendering the web interface. This is a safe and reliable way to get the current version: 

olivetin.example.com/webUiSettings.json

This is a jaon file with several keys, one of those is "CurrentVersion". 

Would that work for you? What options does Homer give you for pulling information out of an API?

**Comment by meonkeys** [comment]
That'll work perfect, thanks!

Homer works well with JSON REST APIs or plain text version string URLs.

If/when https://github.com/bastienwirtz/homer/pull/833 is merged I'll do another PR to add an Olivetin card almost exactly the same, but with

```diff
- this.fetch("/swagger.v1.json")
+ this.fetch("/webUiSettings.json")
```

and

```diff
- this.versionstring = response.info.version;
+ this.versionstring = response.CurrentVersion;
```
