### ISSUE TITLE
StartActionAndWait does not accept arguments

### ISSUE THREAD

**Issue by adnanademovic** [OliveTin/OliveTin#481]
**Describe the bug**
`StartActionAndWait` API call does not support arguments

**To Reproduce**
1. Make API call to `StartActionAndWait` to an action with arguments.
4. See server responding with `"proto: (line 3:5): unknown field \"arguments\""`

**Expected behavior**
As per the documentation, I would expect it to accept arguments in the same way `StartAction` does. In fact, using that command works just fine.

**Comment by adnanademovic** [comment]
The `StartActionAndWaitRequest` protobuffer does not have the arguments field defined. If `StartActionRequest` fields were copied, and the [same loop added in the handler](https://github.com/OliveTin/OliveTin/blob/655a7f205d9d13ad3f5e4eac0c078aa100bb11cf/internal/grpcapi/grpcApi.go#L68-L70), the solution should work.

**Comment by jamesread** [comment]
Hey @adnanademovic , huh, interesting - I'm surprised nobody has found this before (including me). I guess most people are not using the "AndWait" API method.

As well as copying the arguments, the StartActionAndWaitRequest does not even include arguments; https://github.com/OliveTin/OliveTin/blob/655a7f205d9d13ad3f5e4eac0c078aa100bb11cf/OliveTin.proto#L79

So, this is a confirmed bug. I've just pushed a PR for this in #483 which will merge shortly.

Thanks very much for reporting. It will make it into a release this weekend.

**Comment by adnanademovic** [comment]
Thank you for the quick fix!

It might have been the case that I'm the first one to want to do both AndWait and arguments at the same time, as the individual elements worked fine.

Thanks for the great tool. It works wonderfully.

**Comment by jamesread** [comment]
Heya, release 2024.11.14 now includes this fix. Please cpuld uou upgrade, test, and let me know?

**Comment by adnanademovic** [comment]
It works. I tested it everywhere. Thanks!
