### ISSUE TITLE
FR: Support Colour from Command Output

### ISSUE THREAD

**Issue by stellarpower** [OliveTin/OliveTin#487]
I like to use colours in my scripts to help with identifying errors or warnings, as well as helping to scan my own logging inbetween verbose output from individual commands I'm running. It's also really helpful when sharing actions with non-technical users, as it can help them to interpret the output without necessarily understanding the details.

It'd be nice to support displaying any coloured output from the action within the web UI, so that it appears similarly to if I run it from a terminal.

Thanks

**Comment by jamesread** [comment]
@stellarpower , hey, thanks for raising the issue. 

Actually, OliveTin's terminal does already support colored output. For example from my own instance;

![image](https://github.com/user-attachments/assets/2b697764-9bf3-4491-8c1e-f3612d80debd)

It's just rendering ANSI color escape codes; https://www.shellhacks.com/bash-colors/

**Comment by stellarpower** [comment]
Hmm, that's interesting. Mine is getting stripped. I tried using the latest version but it wasn't happy on startup so I quickly searched the code just to see if there was any mention of something that might be happening.

**Comment by stellarpower** [comment]
Yes, I assume the websocket is probably the most likely candidate. There were a few different errors but I didn't manage to capture them all. I had a quick look through the network tab but didn't see a clear source of the failure. What's interesting is that OliveTin's own server is returning that. If I get time I can try to make an MRE and open another issue.

Thanks again, I'll mark this as closed now as it is no longer relevant.

**Comment by jamesread** [comment]
Okay dokey, super. :-) Do raise another issue if you need more help :-)
