### ISSUE TITLE
Task arguments

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#6]
It would be nice to trigger a task with a arguments, such a light brightness, custom timeouts, or similar.

**Describe the solution you'd like**
Available to be set on a per action basis, the ability to specify a couple of arguments.

There are considerable security implications of doing this though - you're basically giving free SSH access to a server if the arguments are abused.

**Additional context**
Originally requested by Luca Heitmann here; https://youtu.be/Ej6NM9rmZtk

**Current status**

- [x] Get the UI to send these values back to the server when starting the action
- [x] Find/Replace variable names (ie, actually use them) on exec
- [x] Fix behavior for undefined variables, unused variables, etc 
- [x] A type system for variables, with several safe/unsafe helpers (ie string_identifier, string_raw_unsafe)
- [x] Code audit for style, cyclo, fmt, etc. 
- [ ] Test the hell out of it

**Feedback**

Feedback is most welcome, even if it's just a :+1: on this comment to indicate you're interested in the feature.

**Comment by excitedbox** [comment]
Yes this would make this useful for so many more use cases. A simple form for adding commands would actually be amazing as well. Being able to input a command with variables as placeholders and maybe even a type field for file/dropdown/textfield etc.

**Comment by jamesread** [comment]
Well, finally, we're looking pretttttty good on task arguments. It required quite a lot more code and changes than I thought. This is a pretty chunky feature for OliveTin.

Code "done", or at least functional. Now lots of testing can begin. I really want to get this release out ASAP though.

**Comment by ashleycawley** [comment]
Great! Nice work @jamesread I will see if I can help out with a bit of testing on the alpha build when I get a chance soon.

**Comment by jamesread** [comment]
This was releaseed in the 2021-11-19 release.
