### ISSUE TITLE
Automatically generate a config file if one has not been found.

### ISSUE THREAD

**Issue by jamesread** [OliveTin/OliveTin#63]
OliveTin could help new users by automatically generating a configuration file. 

However, this has the following issues; 

* It means that the config directory needs to be writable - this breaks the paradime of config being read-only. 
* It also means that if running in a container, OliveTin should inteligently check if it's been given a config directory that is on a separate volume - otherwise it's just writing a config file inside the container, which is pointless.

**Comment by tuxthepenguin84** [comment]
I ran into this issue when I was first deploying OliveTin with docker, but I think this behavior is OK IMO. One thing that might be helpful to new users of OliveTin is to update documentation (https://docs.olivetin.app/install-compose.html) stating that the you need a minimum config.yaml in place for the container to start properly, then you could point users to config.yaml in your Github repo as a starter/example config file to use (https://github.com/OliveTin/OliveTin/blob/main/config.yaml)

**Comment by jamesread** [comment]
Hey @tuxthepenguin84 , sorry that you bumped into this issue. 

I thought I had that in the documentation already actually, but the container instructions were not as good as I thought. I've just made changes in commit https://github.com/OliveTin/docs.olivetin.app/commit/2c3393d46e6d96c48aa437231fbaf30faa0879f2 as you suggested. The changes are now live in the documentation now on these pages in particular;

* https://docs.olivetin.app/install-compose.html 
* https://docs.olivetin.app/install-container.html

Could you take a look and see if you think that would have been helpful enough for you / would help users out in the future?

**Comment by tuxthepenguin84** [comment]
@jamesread changes look good, thanks for the quick response.

**Comment by jamesread** [comment]
Additionall, OliveTin now exposes it's /config directory as a docker volume, making it easier to deploy for novice users.
