### ISSUE TITLE
Action categories on the dashboard

### ISSUE THREAD

**Issue by EzequielBruni** [OliveTin/OliveTin#64]
I'd love to have a way to categorize actions, and separate them visually on the page. Something like this:

![OliveTin Categories](https://user-images.githubusercontent.com/1215780/168461310-9120c677-3f59-4b66-a9fe-f4e5019c7f79.png)

Give it more of a dashboard feel, I guess.

----

Unrelated: I'm going to be writing an OliveTin doc specifically for Rocky Linux's documentation, but I had a couple more ideas. Would you like any of the following for your own doc site?

1. A tutorial on installing OliveTin inside an LXD container (with the deb/rpm binaries).
2. A guide on manually installing OliveTin on Alpine Linux, assuming I can make it work? (Update: I made it work.)

**Comment by EzequielBruni** [comment]
@jamesread I can tell you (having already [written the doc about it](https://docs.rockylinux.org/guides/automation/olivetin/)) that OliveTin works just fine on Rocky 8. Should be just fine on 9 as well. I didn't exactly mention mention "Arch" Linux, but that's pretty cool. As said, I did make it work on Alpine just fine. A while back, I actually sent you the service file for openrc/busybox style OSs, of which Alpine is one.

As for the categories, I'd sort of love to have both options, but multiple dashboards would do just fine.

I can add an LXD guide to my to-do list (and perhaps a separate one for Alpine).

**Comment by jamesread** [comment]
Hey, I've just had some time to work on this, and wanted to share a development video that calls out some relevant changes. Does this fix the issue for you?

https://youtu.be/vWAD04Wpa8U

**Comment by EzequielBruni** [comment]
While not exactly what I had envisioned, in nonetheless solves the issue of categorization and the visual separation of concerns. Love it !

**Comment by jamesread** [comment]
Hey @EzequielBruni , great to hear that you love it - but you said it's not exactly what you had in mind; I'm curious - what did you have in mind? 🤔

**Comment by jamesread** [comment]
For anyone else looking at this in the future, this was added in the 2024.02.27 release, and it is called "fieldsets": https://docs.olivetin.app/fieldsets.html
