### ISSUE TITLE
Console Window Showing output of last executed command in main window

### ISSUE THREAD

**Issue by samcro1967** [OliveTin/OliveTin#66]
**Is your feature request related to a problem? Please describe.**
I would like to be able to see the output of the last command that was executed without having to go to the logs and expanding stdout and stderr.

**Describe the solution you'd like**
I would like a console window on the actions tab that displays the output of the last executed command with stdout and stderr consolidated in order with a scroll bar.

**Comment by jamesread** [comment]
Duplicate of #43
