### ISSUE TITLE
Allow api calls from url alone

### ISSUE THREAD

**Issue by 33masterman33** [OliveTin/OliveTin#70]
I think an api using a url scheme like http://olivetin.webapps.teratan.lan/api/StartAction?Action%20Name would be a lot easier use. While sending a post request with data works it limits the amount of services that can call the api such as other web based services. Is this something that’s reasonable to do?

**Comment by jamesread** [comment]
Hey @33masterman33 , thanks for taking your time to write this up. 

I suppose this is possible, although it isn't really the "right way" - GET requests should not have side effects. 

However, I could see how this might be useful. Would you mind sharing a bit more detail about what app you're using that makes GET requests easier than POST requests?

**Comment by 33masterman33** [comment]
I was trying to use a dashboard homepage and call the api using one of the buttons. I couldn't find a dashboard that would natively let me use curl or wget to send the post request. I'd like to be able to organize all my links and commands on one page. I tried to do it in js but either my browser was blocking it or I just don't know what I'm doing as I'm a beginner at this stuff. I can definitely see that since this is not standard practice you may not want to implement it. If you know of another solution I'd be happy to try that too. Thank you!

**Comment by jamesread** [comment]
Hey @33masterman33 , I've been thinking about this a bit more, and it makes the code a bit messy if I were to implement it. 

Is this still something you need? It certainly is possible to implement a POST request via Javascript at least.

**Comment by jamesread** [comment]
Closing, as there's not been any feedback on this issue, nobody else has asked for it, and I cannot think of a good reason to do it.

I totally have an open mind if someone else would like to re-open this issue with an interesting use case for why it might be needed.

The OliveTin API does of course allow starting actions via a POST request; https://docs.olivetin.app/api.html

**Comment by kmcbride3** [comment]
I'd find this feature helpful to use as a webhook for other services - still as a POST request, but having a direct URL to a specific action would allow me to create scripts/processes via OliveTin that could then be triggered by an uptime monitoring solution like Uptime Kuma (https://github.com/louislam/uptime-kuma).

So the flow would be as follows:

1. Uptime Kuma detects a monitored service is down on my home network
2. Uptime Kuma sends a request to OliveTin as a webhook notification to trigger an action
3. OliveTin receives POST request and run the requested action

This would open up some automated self-healing options. Right now, the process flow is that Uptime Kuma sends me a notification, then I manually open up OliveTin on a device and manually run the action as a first step to troubleshooting/attempting to resolve the issue.

**Comment by jamesread** [comment]
@kmcbride3  Okay, was that just the weirdest, spookiest co-incidence that we just commented at exactly the same time?! I just closed as lack of interest, and then I saw you comment with my post?! Weird...

**Comment by kmcbride3** [comment]
> 

Wow, that _IS_ spooky!

Does my use case make sense, or have I missed something obvious that would enable what I'm trying to do already?

**Comment by jamesread** [comment]
@kmcbride3 , So weird. Nothing happens in 7 months, and then within the same minute we both comment. Anyway! 

So, I like that you have an interesting use case - using OliveTin for triggering self-healing. That's cool. 

However, /api/StartAction would be a POST request with a body, and the example from Uptime Kuma would simply be a POST request to a different URL? Something like /api/StartActionHooks/RestartFirewall ?

**Comment by kmcbride3** [comment]
Uptime Kuma strictly fires out alerts/notifications when it detects a service is down through existing services like Email, SMS, Pushover, Telegram, etc... however, it does have the option to send a notification via webhook using a configurable URL.

It automatically includes some details about the service outage in the body of the POST request it sends, but for these purposes, I would ignore any data included and just fire off the action. For simplicity, this would only apply to actions without additional arguments.

This is where I thought OliveTin could come into play. If I set up an action in OliveTin (whether it's running an SSH command or simply restarting a docker container), and could call/trigger that action to run directly (by using its direct URL as the webhook URL in Uptime Kuma), I could potentially have some self-healing functionality (or at least do the obvious/easy things first before it escalates to manual intervention).

**Comment by jamesread** [comment]
I think I'm starting to understand - I assume Uptime Kuma doesn't allow you to customize the POST body (to set ActionName - because the POST body includes details about the alert) - it just let's you set a webhook URL? Hence the need for a webhook?

If so, it means OliveTin hooks to start actions could only allow simple start requests - no arguments, etc, it would have to ignore the POST body effectively.

**Comment by kmcbride3** [comment]
Yes, exactly. It doesn't allow any customization on the POST body - though it does allow for custom headers, though that's probably not the right design pattern...

I'd expect that this would only work for simple start requests, yes.

**Comment by kmcbride3** [comment]
Stumbled across another project (https://github.com/ncarlier/webhookd) that allows for parameters to be passed via either the HTTP request headers or URL request parameters - either of which could be used to enable the more complex requests with arguments - thought it was an interesting approach.
