### ISSUE TITLE
Arm64 / armv7 docker image?

### ISSUE THREAD

**Issue by kjboa** [OliveTin/OliveTin#8]
Hi, your project looks really promising and would be very useful for lots of people running SBCs as servers. However at the moment there is no docker image for these platforms. If you could create one that would be awesome!

**Comment by kjboa** [comment]
Currently i'm running an old x86 server and a raspi400. Of course i'd love to give you direct feedback but the only discord link i found is broken... .For now i think i'm gonna try to find the .deb

**Comment by jamesread** [comment]
@kjboa That's embarrassing about the Discord link - I've fixed that for now.

I'm taking a look at pushing the ARM Docker images once again - do let me know if the .deb works for now. 

Thanks again for your interest in OliveTin :-)

**Comment by jamesread** [comment]
https://github.com/OliveTin/OliveTin/tree/arm-docker-images

**Comment by jamesread** [comment]
Ref https://github.com/nicholaswilde/helm-charts/issues/57

**Comment by kjboa** [comment]
> 
> 
> @kjboa That's embarrassing about the Discord link - I've fixed that for now.
> 
> I'm taking a look at pushing the ARM Docker images once again - do let me know if the .deb works for now.
> 
> Thanks again for your interest in OliveTin :-)

I have been using the .deb file for a while now; works fine and i quite enjoy olivetin.

**Comment by jamesread** [comment]
With the 2021-11-19 release this is finally supported. It took me a long time to work out multiarch container builds.

**Comment by kjboa** [comment]
> With the 2021-11-19 release this is finally supported. It took me a long time to work out multiarch container builds. 

Great! Thanks for your work
