### ISSUE TITLE
Status command

### ISSUE THREAD

**Issue by slavaGanzin** [OliveTin/OliveTin#84]
Hi, awesome project, btw. 

Would be great to have status/health check command that would be running with configurable interval. 

For example if you have command 

systemctl restart service

it would be beneficial to display status inside olive tin. Using old good:

systemctl status service

p.s. I prefer to write PRs and not issues. But I’m not skilled in Go, so it is what it is

**Comment by jamesread** [comment]
Hey @slavaGanzin , heh, actually I started out writing a monitoring system first - called Upsilon Project, almost 10 years ago, which I started in Java. When I was first learning Go, I was trying to reimplement Upsilon, and that is what OliveTin became - but a much much simplier version of Upsilon project (which I did now also port to Go - http://upsilonproject.io / github.com/upsilonproject ). However I absolutely would not recommend using it for more reasons than I can go into here!

As for OliveTin, the request to run actions / commands on a schedule is something that has come up a few times before. I was always worried about reimplementing cron. However, with most systems now using systemd, and having to use systemd timers - they're actaully a real pain to setup and use, so I might revisit this idea. 

What do you think about something like this?;

```
actions:
  - name: check httpd
    shell: systemctl is-running httpd
    schedule:
      - every 5 minutes
```

**Comment by slavaGanzin** [comment]
Great, but I thought it be handy if monitoring would be joined with command itself. 

And status can be displayed with color of command button/text inside of a button. 

Like “restart nginx (running)”

**Comment by slavaGanzin** [comment]
Funny, I recently started working on https://helpmetest.app/

monitoring using browser tests. Very WIP, so as with Upsilon, do not recommend it for production

**Comment by jamesread** [comment]
For anyone reading this now, OliveTin does now support schedules (cron); https://docs.olivetin.app/exec-cron.html
