### ISSUE TITLE
Feature request: run scripts at startup

### ISSUE THREAD

**Issue by flammable** [OliveTin/OliveTin#92]
**Is your feature request related to a problem? Please describe.**
OliveTin doesn't always include the executables I'd like to run.

**Describe the solution you'd like**
I'd really like the ability to automatically run scripts when OliveTin is started, [sort of like how the LinuxServer containers have implemented](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers). This would allow me to install executables within the container each time it's rebuilt.

I used this with another Docker image I used up until recently - I needed some additional stuff installed, so I wrote a small script to install the extras each time the container was rebuilt.

**Describe alternatives you've considered**
For now, I can do this manually, or script it myself when building the container.

**Additional context**
#89 made me think of this - instead of having to include `docker compose` in the image, it'd be really great if I could just install it myself, automatically, each time the container is built. This would keep the image small and free of additional security issues, depending on what users might want to have installed.

Thanks!

**Comment by jamesread** [comment]
Huh, that's an extremely good idea - I'm not sure why I've not seen more containers follow that pattern (although I do use quite a lot of LSIO containers myself as well). It would make future extensibility a lot easier.

I think it would work well, to put the logs of the startup script directly into the OliveTin logs, as well - making it easier to debug for novice users. 

Users could simply create a "startupScripts" folder in their /config/ volume, and OliveTin could just iterate over them at startup.

**Comment by jamesread** [comment]
Actually, just thinking out loud, does it make more sense to have startup scripts as one-liners in config.yaml?

**Comment by flammable** [comment]
Thanks! LSIO actually [has the scripts sit outside of the config folder](https://info.linuxserver.io/issues/2022-12-22-custom-files/) - it sounds like that's mostly to avoid permissions issues, but it's also good security to mount as a separate read-only volume.

I totally agree about having the scripts log their output to the OliveTin container's logs! If I were looking for output, I think that's where I'd check first.

Thanks again for checking this out, and for OliveTin in the first place! I got it working last night and I'm really excited about how much easier it's going to make things here. 😄

**Comment by jamesread** [comment]
Hey @flammable - I actually implemented a little while ago and forgot to mention it here. It's documented here; https://docs.olivetin.app/exec-startup.html - Do you think that meets your needs?

**Comment by flammable** [comment]
Thanks! I think you mentioned the new functionality in the documentation PR I submitted - I've been using it for a little while now, and it works great. Thanks!
