### ISSUE TITLE
Allow renames for JWT claims

### ISSUE THREAD

**Issue by macabrus** [OliveTin/OliveTin#96]
Hello,
it'd be cool if we had following config properties:
```
authJwtClaimUsername: custom_username_property_name
authJwtClaimUsergroup: custom_role_array_property_name
```

It improves interoperability with other software. Consider similar issue and how Grafana upstream handles it in `.ini` behind caddy proxy for example:
https://github.com/greenpau/caddy-security/issues/173#issuecomment-1290264073

Thanks in advance!

**Comment by macabrus** [comment]
Please check: https://github.com/OliveTin/OliveTin/pull/97
I drafted a solution.

**Comment by jamesread** [comment]
Hey @macabrus , thanks very much indeed for raising this issue and PR - I'm happy to accept this.

I had previously only been testing again Organizr, which does this jwt auth. I'm just curious, what were you trying to integrate against? 

We'll need to document this too - created https://github.com/OliveTin/docs.olivetin.app/issues/8 as a placeholder.

**Comment by macabrus** [comment]
I was trying to proxy it through Caddy Security plugin which uses "sub" for the username in JWT, it supports [custom properties](https://authp.github.io/docs/authenticate/user-transforms#inject-custom-claims) but I haven't found a way to map properties from one name to another so I thought this addition would be easier.

**Comment by macabrus** [comment]
I noticed another error ⚠️ in strings where "usergroup" is sourced from "password" metadata (?) so i made another pr to fix that: https://github.com/OliveTin/OliveTin/pull/99

**Comment by jamesread** [comment]
@macabrus thank you very much for your patience here, I just wanted to say thanks again for your work on #97 and #99 . 

I've added some basic documentation too, at https://docs.olivetin.app/jwt.html that should help people find this in the future. 

Closing this now, but thanks again for raising it, and fixing it!
