### ISSUE TITLE
callback error Error: Proxy Error

### ISSUE THREAD

**Issue by g1lby** [OliveTin/OliveTin#98]
Hi everyone!

I just started playing around with OliveTin and wanted to execute some Ansible playbooks thorugh it. 

My setup is as follows:
Rocky 9 inside a VPC in AWS behind a firewall, reachable within VPN
httpd with proxy setup, auto redirect to https with a wildcard certificate
OliveTin installed via .rpm package

My playbooks are quite heavy and nested (creating ec2 instance, network interfaces, route53 records, system configuration...), that's why I set the timeout value to 600.
When running the commands on the bash, everything is executed successfully. When executed through the web interface I get this message in the network tab of the developer tools of my browser (Firefox):
`callback error Error: Proxy Error
    startAction https://admin.domain.tld/js/ActionButton.js:80
[ActionButton.js:112:13](https://admin.domain.tld/js/ActionButton.js)
    onActionError https://admin.domain.tld/js/ActionButton.js:112
    startAction https://admin.domain.tld /js/ActionButton.js:96`

And this is from my /var/log/messages:
`Jan 11 06:15:15 admin OliveTin[645]: 2023/01/11 06:15:15 http: proxy error: context canceled`

Here is my appconfig:
`# There is a built-in micro proxy that will host the webui and REST API all on
# one port (this is called the "Single HTTP Frontend") and means you just need
# one open port in the container/firewalls/etc.
#
# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337

# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

# Actions (buttons) to show up on the WebUI:
actions:
- title: Create new customer backend instance (EC2)
  shell: echo "{{ vpc_hostname }}.domain.tld" >> /etc/ansible/inventory/backends && ansible-playbook /etc/ansible/ec2-create-backend.yaml -i /etc/ansible/inventory/backends --extra-vars "vpc_hostname={{ vpc_hostname }}.domain.tld vpc_subnetid={{ vpc_subnetid }} instance_type={{ instance_type }} backend_fqdn_ext={{ backend_fqdn_ext }}.domain.tld" --extra-vars '@/etc/ansible/become.yaml'  --tags=ec2-create -v > /var/log/backend_ansible.log
  icon: "&#x1F1E6"
  timeout: 600
  arguments:
    - name: backend_fqdn_ext
      title: Public backend URL hash
      type: ascii_identifier
      description: "Omit https:// and .domain.tld"

    - name: vpc_hostname
      title: Hostname
      type: ascii_identifier
      description: "Omit .domain.tld, it will be appended automatically. Stick to name convention: <customer>-backend-01.[prod|stag]"

    - name: vpc_subnetid
      title: VPC Subnet ID
      type: ascii_identifier
      description: Get this from documentation or AWS VPC console

    - name: instance_type
      title: Sizing
      choices:
          - title: S - c5.2xlarge
            value: c5.2xlarge

          - title: M - c5.4xlarge
            value: c5.4xlarge

          - title: L - c5.9xlarge
            value: c5.9xlarge`

Here are my httpd configs:
000-domain.tld.conf

`<VirtualHost *:80>
  ProxyPreserveHost On
  ProxyRequests Off
  ServerName admin.domain.tld
  ProxyPass / http://localhost:1337/
  ProxyPassReverse / http://localhost:1337/
RewriteEngine on
RewriteCond %{SERVER_NAME} =admin.domain.tld
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>`

001-https-domain.tld.conf
<IfModule mod_ssl.c>
  <VirtualHost *:443>
    ProxyPreserveHost On
    ProxyRequests Off
    ServerName admin.domain.tld
    ProxyPass / http://localhost:1337/
    ProxyPassReverse /api http://localhost:1337/
  
  SSLEngine On
  SSLCertificateFile /etc/pki/tls/certs/admin.domain.tld.pem
  SSLCertificateKeyFile /etc/pki/tls/private/admin.domain.tld.key
  </VirtualHost>
  </IfModule>

Any help or hint would be so much appreciated :)

**Comment by jamesread** [comment]
Hey @g1lby , thanks for reporting this issue, and sorry that you've hit it :-( 

I'd need to do some testing, but my hypothesis is that the internal proxy within OliveTin is timing out instead of waiting for the the action to execute - there are two contexts here, and I think the proxy context probably has a lower timeout. 

How long does the action run for? I assume it's not cancelling immediately, but maybe after 60 seconds or so?

**Comment by g1lby** [comment]
Hi James,
thanks for looking into it!
Yes, if I'd had to guess, it might be something around 1-2 mins until the button flashes up red once in the webgui and then the command breaks with the errors mentioned.

**Comment by jamesread** [comment]
Hey @g1lby , now in more recent versions of OliveTin, actions are executed asyncronously, meaning that the web interface asks the API to execute the action, and the API call returns immediately - the web interface then waits for updates via websocket, or polls. 

Would you mind testing this again now with a recent version of OliveTin? Thanks.
